/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/api/client.ts";
import type { MessagesListQueryResponse, MessagesListQueryParams } from "../../types/MessagesList.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/api/client.ts";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const messagesListQueryKey = (params?: MessagesListQueryParams) => [{ url: '/api/messages/' }, ...(params ? [params] : [])] as const

export type MessagesListQueryKey = ReturnType<typeof messagesListQueryKey>

/**
 * {@link /api/messages/}
 */
export async function messagesList(params?: MessagesListQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<MessagesListQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/api/messages/`, params, ... requestConfig })  
  return res.data
}

export function messagesListQueryOptions(params?: MessagesListQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = messagesListQueryKey(params)
  return queryOptions<MessagesListQueryResponse, ResponseErrorConfig<Error>, MessagesListQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return messagesList(params, config)
   },
  })
}

/**
 * {@link /api/messages/}
 */
export function useMessagesList<TData = MessagesListQueryResponse, TQueryData = MessagesListQueryResponse, TQueryKey extends QueryKey = MessagesListQueryKey>(params?: MessagesListQueryParams, options: 
{
  query?: Partial<QueryObserverOptions<MessagesListQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? messagesListQueryKey(params)

  const query = useQuery({
   ...messagesListQueryOptions(params, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}