/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/api/client.ts";
import type { MessagesDestroyMutationResponse, MessagesDestroyPathParams } from "../../types/MessagesDestroy.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/api/client.ts";
import type { UseMutationOptions, QueryClient } from "@tanstack/react-query";
import { useMutation } from "@tanstack/react-query";

export const messagesDestroyMutationKey = () => [{ url: '/api/messages/:id/' }] as const

export type MessagesDestroyMutationKey = ReturnType<typeof messagesDestroyMutationKey>

/**
 * {@link /api/messages/:id/}
 */
export async function messagesDestroy(id: MessagesDestroyPathParams["id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<MessagesDestroyMutationResponse, ResponseErrorConfig<Error>, unknown>({ method : "DELETE", url : `/api/messages/${id}/`, ... requestConfig })  
  return res.data
}

/**
 * {@link /api/messages/:id/}
 */
export function useMessagesDestroy<TContext>(options: 
{
  mutation?: UseMutationOptions<MessagesDestroyMutationResponse, ResponseErrorConfig<Error>, {id: MessagesDestroyPathParams["id"]}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? messagesDestroyMutationKey()

  return useMutation<MessagesDestroyMutationResponse, ResponseErrorConfig<Error>, {id: MessagesDestroyPathParams["id"]}, TContext>({
    mutationFn: async({ id }) => {
      return messagesDestroy(id, config)
    },
    mutationKey,
    ...mutationOptions
  }, queryClient)
}