/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/api/client.ts";
import type { MessagesPartialUpdateMutationRequest, MessagesPartialUpdateMutationResponse, MessagesPartialUpdatePathParams } from "../../types/MessagesPartialUpdate.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/api/client.ts";
import type { UseMutationOptions, QueryClient } from "@tanstack/react-query";
import { useMutation } from "@tanstack/react-query";

export const messagesPartialUpdateMutationKey = () => [{ url: '/api/messages/:id/' }] as const

export type MessagesPartialUpdateMutationKey = ReturnType<typeof messagesPartialUpdateMutationKey>

/**
 * {@link /api/messages/:id/}
 */
export async function messagesPartialUpdate(id: MessagesPartialUpdatePathParams["id"], data?: MessagesPartialUpdateMutationRequest, config: Partial<RequestConfig<MessagesPartialUpdateMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<MessagesPartialUpdateMutationResponse, ResponseErrorConfig<Error>, MessagesPartialUpdateMutationRequest>({ method : "PATCH", url : `/api/messages/${id}/`, data : requestData, ... requestConfig })  
  return res.data
}

/**
 * {@link /api/messages/:id/}
 */
export function useMessagesPartialUpdate<TContext>(options: 
{
  mutation?: UseMutationOptions<MessagesPartialUpdateMutationResponse, ResponseErrorConfig<Error>, {id: MessagesPartialUpdatePathParams["id"], data?: MessagesPartialUpdateMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<MessagesPartialUpdateMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? messagesPartialUpdateMutationKey()

  return useMutation<MessagesPartialUpdateMutationResponse, ResponseErrorConfig<Error>, {id: MessagesPartialUpdatePathParams["id"], data?: MessagesPartialUpdateMutationRequest}, TContext>({
    mutationFn: async({ id, data }) => {
      return messagesPartialUpdate(id, data, config)
    },
    mutationKey,
    ...mutationOptions
  }, queryClient)
}