/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/api/client.ts";
import type { MessagesUpdateMutationRequest, MessagesUpdateMutationResponse, MessagesUpdatePathParams } from "../../types/MessagesUpdate.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/api/client.ts";
import type { UseMutationOptions, QueryClient } from "@tanstack/react-query";
import { useMutation } from "@tanstack/react-query";

export const messagesUpdateMutationKey = () => [{ url: '/api/messages/:id/' }] as const

export type MessagesUpdateMutationKey = ReturnType<typeof messagesUpdateMutationKey>

/**
 * {@link /api/messages/:id/}
 */
export async function messagesUpdate(id: MessagesUpdatePathParams["id"], data: MessagesUpdateMutationRequest, config: Partial<RequestConfig<MessagesUpdateMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<MessagesUpdateMutationResponse, ResponseErrorConfig<Error>, MessagesUpdateMutationRequest>({ method : "PUT", url : `/api/messages/${id}/`, data : requestData, ... requestConfig })  
  return res.data
}

/**
 * {@link /api/messages/:id/}
 */
export function useMessagesUpdate<TContext>(options: 
{
  mutation?: UseMutationOptions<MessagesUpdateMutationResponse, ResponseErrorConfig<Error>, {id: MessagesUpdatePathParams["id"], data: MessagesUpdateMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<MessagesUpdateMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? messagesUpdateMutationKey()

  return useMutation<MessagesUpdateMutationResponse, ResponseErrorConfig<Error>, {id: MessagesUpdatePathParams["id"], data: MessagesUpdateMutationRequest}, TContext>({
    mutationFn: async({ id, data }) => {
      return messagesUpdate(id, data, config)
    },
    mutationKey,
    ...mutationOptions
  }, queryClient)
}