/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/api/client.ts";
import type { MessagesRetrieveQueryResponse, MessagesRetrievePathParams } from "../../types/MessagesRetrieve.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/api/client.ts";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const messagesRetrieveSuspenseQueryKey = (id: MessagesRetrievePathParams["id"]) => [{ url: '/api/messages/:id/', params: {id:id} }] as const

export type MessagesRetrieveSuspenseQueryKey = ReturnType<typeof messagesRetrieveSuspenseQueryKey>

/**
 * {@link /api/messages/:id/}
 */
export async function messagesRetrieveSuspense(id: MessagesRetrievePathParams["id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<MessagesRetrieveQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/api/messages/${id}/`, ... requestConfig })  
  return res.data
}

export function messagesRetrieveSuspenseQueryOptions(id: MessagesRetrievePathParams["id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = messagesRetrieveSuspenseQueryKey(id)
  return queryOptions<MessagesRetrieveQueryResponse, ResponseErrorConfig<Error>, MessagesRetrieveQueryResponse, typeof queryKey>({
   enabled: !!(id),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return messagesRetrieveSuspense(id, config)
   },
  })
}

/**
 * {@link /api/messages/:id/}
 */
export function useMessagesRetrieveSuspense<TData = MessagesRetrieveQueryResponse, TQueryKey extends QueryKey = MessagesRetrieveSuspenseQueryKey>(id: MessagesRetrievePathParams["id"], options: 
{
  query?: Partial<UseSuspenseQueryOptions<MessagesRetrieveQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? messagesRetrieveSuspenseQueryKey(id)

  const query = useSuspenseQuery({
   ...messagesRetrieveSuspenseQueryOptions(id, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}