/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/api/client.ts";
import type { MessagesRetrieveQueryResponse, MessagesRetrievePathParams } from "../../types/MessagesRetrieve.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/api/client.ts";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const messagesRetrieveQueryKey = (id: MessagesRetrievePathParams["id"]) => [{ url: '/api/messages/:id/', params: {id:id} }] as const

export type MessagesRetrieveQueryKey = ReturnType<typeof messagesRetrieveQueryKey>

/**
 * {@link /api/messages/:id/}
 */
export async function messagesRetrieve(id: MessagesRetrievePathParams["id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<MessagesRetrieveQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/api/messages/${id}/`, ... requestConfig })  
  return res.data
}

export function messagesRetrieveQueryOptions(id: MessagesRetrievePathParams["id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = messagesRetrieveQueryKey(id)
  return queryOptions<MessagesRetrieveQueryResponse, ResponseErrorConfig<Error>, MessagesRetrieveQueryResponse, typeof queryKey>({
   enabled: !!(id),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return messagesRetrieve(id, config)
   },
  })
}

/**
 * {@link /api/messages/:id/}
 */
export function useMessagesRetrieve<TData = MessagesRetrieveQueryResponse, TQueryData = MessagesRetrieveQueryResponse, TQueryKey extends QueryKey = MessagesRetrieveQueryKey>(id: MessagesRetrievePathParams["id"], options: 
{
  query?: Partial<QueryObserverOptions<MessagesRetrieveQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? messagesRetrieveQueryKey(id)

  const query = useQuery({
   ...messagesRetrieveQueryOptions(id, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}