/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/api/client.ts";
import type { TaskStatusTaskStatusWorkflowRetrieveQueryResponse } from "../../types/TaskStatusTaskStatusWorkflowRetrieve.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/api/client.ts";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const taskStatusTaskStatusWorkflowRetrieveSuspenseQueryKey = () => [{ url: '/api/task-status/task-status-workflow/' }] as const

export type TaskStatusTaskStatusWorkflowRetrieveSuspenseQueryKey = ReturnType<typeof taskStatusTaskStatusWorkflowRetrieveSuspenseQueryKey>

/**
 * {@link /api/task-status/task-status-workflow/}
 */
export async function taskStatusTaskStatusWorkflowRetrieveSuspense(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<TaskStatusTaskStatusWorkflowRetrieveQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/api/task-status/task-status-workflow/`, ... requestConfig })  
  return res.data
}

export function taskStatusTaskStatusWorkflowRetrieveSuspenseQueryOptions(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = taskStatusTaskStatusWorkflowRetrieveSuspenseQueryKey()
  return queryOptions<TaskStatusTaskStatusWorkflowRetrieveQueryResponse, ResponseErrorConfig<Error>, TaskStatusTaskStatusWorkflowRetrieveQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return taskStatusTaskStatusWorkflowRetrieveSuspense(config)
   },
  })
}

/**
 * {@link /api/task-status/task-status-workflow/}
 */
export function useTaskStatusTaskStatusWorkflowRetrieveSuspense<TData = TaskStatusTaskStatusWorkflowRetrieveQueryResponse, TQueryKey extends QueryKey = TaskStatusTaskStatusWorkflowRetrieveSuspenseQueryKey>(options: 
{
  query?: Partial<UseSuspenseQueryOptions<TaskStatusTaskStatusWorkflowRetrieveQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? taskStatusTaskStatusWorkflowRetrieveSuspenseQueryKey()

  const query = useSuspenseQuery({
   ...taskStatusTaskStatusWorkflowRetrieveSuspenseQueryOptions(config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}