/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/api/client.ts";
import type { TaskStatusCreateMutationRequest, TaskStatusCreateMutationResponse } from "../../types/TaskStatusCreate.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/api/client.ts";
import type { UseMutationOptions, QueryClient } from "@tanstack/react-query";
import { useMutation } from "@tanstack/react-query";

export const taskStatusCreateMutationKey = () => [{ url: '/api/task-status/' }] as const

export type TaskStatusCreateMutationKey = ReturnType<typeof taskStatusCreateMutationKey>

/**
 * {@link /api/task-status/}
 */
export async function taskStatusCreate(data: TaskStatusCreateMutationRequest, config: Partial<RequestConfig<TaskStatusCreateMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<TaskStatusCreateMutationResponse, ResponseErrorConfig<Error>, TaskStatusCreateMutationRequest>({ method : "POST", url : `/api/task-status/`, data : requestData, ... requestConfig })  
  return res.data
}

/**
 * {@link /api/task-status/}
 */
export function useTaskStatusCreate<TContext>(options: 
{
  mutation?: UseMutationOptions<TaskStatusCreateMutationResponse, ResponseErrorConfig<Error>, {data: TaskStatusCreateMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<TaskStatusCreateMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? taskStatusCreateMutationKey()

  return useMutation<TaskStatusCreateMutationResponse, ResponseErrorConfig<Error>, {data: TaskStatusCreateMutationRequest}, TContext>({
    mutationFn: async({ data }) => {
      return taskStatusCreate(data, config)
    },
    mutationKey,
    ...mutationOptions
  }, queryClient)
}