/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/api/client.ts";
import type { TaskStatusTaskStatusWorkflowRetrieveQueryResponse } from "../../types/TaskStatusTaskStatusWorkflowRetrieve.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/api/client.ts";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const taskStatusTaskStatusWorkflowRetrieveQueryKey = () => [{ url: '/api/task-status/task-status-workflow/' }] as const

export type TaskStatusTaskStatusWorkflowRetrieveQueryKey = ReturnType<typeof taskStatusTaskStatusWorkflowRetrieveQueryKey>

/**
 * {@link /api/task-status/task-status-workflow/}
 */
export async function taskStatusTaskStatusWorkflowRetrieve(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<TaskStatusTaskStatusWorkflowRetrieveQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/api/task-status/task-status-workflow/`, ... requestConfig })  
  return res.data
}

export function taskStatusTaskStatusWorkflowRetrieveQueryOptions(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = taskStatusTaskStatusWorkflowRetrieveQueryKey()
  return queryOptions<TaskStatusTaskStatusWorkflowRetrieveQueryResponse, ResponseErrorConfig<Error>, TaskStatusTaskStatusWorkflowRetrieveQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return taskStatusTaskStatusWorkflowRetrieve(config)
   },
  })
}

/**
 * {@link /api/task-status/task-status-workflow/}
 */
export function useTaskStatusTaskStatusWorkflowRetrieve<TData = TaskStatusTaskStatusWorkflowRetrieveQueryResponse, TQueryData = TaskStatusTaskStatusWorkflowRetrieveQueryResponse, TQueryKey extends QueryKey = TaskStatusTaskStatusWorkflowRetrieveQueryKey>(options: 
{
  query?: Partial<QueryObserverOptions<TaskStatusTaskStatusWorkflowRetrieveQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? taskStatusTaskStatusWorkflowRetrieveQueryKey()

  const query = useQuery({
   ...taskStatusTaskStatusWorkflowRetrieveQueryOptions(config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}