/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/api/client.ts";
import type { TaskStatusListQueryResponse } from "../../types/TaskStatusList.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/api/client.ts";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const taskStatusListQueryKey = () => [{ url: '/api/task-status/' }] as const

export type TaskStatusListQueryKey = ReturnType<typeof taskStatusListQueryKey>

/**
 * {@link /api/task-status/}
 */
export async function taskStatusList(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<TaskStatusListQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/api/task-status/`, ... requestConfig })  
  return res.data
}

export function taskStatusListQueryOptions(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = taskStatusListQueryKey()
  return queryOptions<TaskStatusListQueryResponse, ResponseErrorConfig<Error>, TaskStatusListQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return taskStatusList(config)
   },
  })
}

/**
 * {@link /api/task-status/}
 */
export function useTaskStatusList<TData = TaskStatusListQueryResponse, TQueryData = TaskStatusListQueryResponse, TQueryKey extends QueryKey = TaskStatusListQueryKey>(options: 
{
  query?: Partial<QueryObserverOptions<TaskStatusListQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? taskStatusListQueryKey()

  const query = useQuery({
   ...taskStatusListQueryOptions(config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}