/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/api/client.ts";
import type { TaskStatusDestroyMutationResponse, TaskStatusDestroyPathParams } from "../../types/TaskStatusDestroy.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/api/client.ts";
import type { UseMutationOptions, QueryClient } from "@tanstack/react-query";
import { useMutation } from "@tanstack/react-query";

export const taskStatusDestroyMutationKey = () => [{ url: '/api/task-status/:id/' }] as const

export type TaskStatusDestroyMutationKey = ReturnType<typeof taskStatusDestroyMutationKey>

/**
 * {@link /api/task-status/:id/}
 */
export async function taskStatusDestroy(id: TaskStatusDestroyPathParams["id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<TaskStatusDestroyMutationResponse, ResponseErrorConfig<Error>, unknown>({ method : "DELETE", url : `/api/task-status/${id}/`, ... requestConfig })  
  return res.data
}

/**
 * {@link /api/task-status/:id/}
 */
export function useTaskStatusDestroy<TContext>(options: 
{
  mutation?: UseMutationOptions<TaskStatusDestroyMutationResponse, ResponseErrorConfig<Error>, {id: TaskStatusDestroyPathParams["id"]}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? taskStatusDestroyMutationKey()

  return useMutation<TaskStatusDestroyMutationResponse, ResponseErrorConfig<Error>, {id: TaskStatusDestroyPathParams["id"]}, TContext>({
    mutationFn: async({ id }) => {
      return taskStatusDestroy(id, config)
    },
    mutationKey,
    ...mutationOptions
  }, queryClient)
}