/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/api/client.ts";
import type { TaskStatusRetrieveQueryResponse, TaskStatusRetrievePathParams } from "../../types/TaskStatusRetrieve.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/api/client.ts";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const taskStatusRetrieveSuspenseQueryKey = (id: TaskStatusRetrievePathParams["id"]) => [{ url: '/api/task-status/:id/', params: {id:id} }] as const

export type TaskStatusRetrieveSuspenseQueryKey = ReturnType<typeof taskStatusRetrieveSuspenseQueryKey>

/**
 * {@link /api/task-status/:id/}
 */
export async function taskStatusRetrieveSuspense(id: TaskStatusRetrievePathParams["id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<TaskStatusRetrieveQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/api/task-status/${id}/`, ... requestConfig })  
  return res.data
}

export function taskStatusRetrieveSuspenseQueryOptions(id: TaskStatusRetrievePathParams["id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = taskStatusRetrieveSuspenseQueryKey(id)
  return queryOptions<TaskStatusRetrieveQueryResponse, ResponseErrorConfig<Error>, TaskStatusRetrieveQueryResponse, typeof queryKey>({
   enabled: !!(id),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return taskStatusRetrieveSuspense(id, config)
   },
  })
}

/**
 * {@link /api/task-status/:id/}
 */
export function useTaskStatusRetrieveSuspense<TData = TaskStatusRetrieveQueryResponse, TQueryKey extends QueryKey = TaskStatusRetrieveSuspenseQueryKey>(id: TaskStatusRetrievePathParams["id"], options: 
{
  query?: Partial<UseSuspenseQueryOptions<TaskStatusRetrieveQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? taskStatusRetrieveSuspenseQueryKey(id)

  const query = useSuspenseQuery({
   ...taskStatusRetrieveSuspenseQueryOptions(id, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}