/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/api/client.ts";
import type { TaskStatusRetrieveQueryResponse, TaskStatusRetrievePathParams } from "../../types/TaskStatusRetrieve.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/api/client.ts";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const taskStatusRetrieveQueryKey = (id: TaskStatusRetrievePathParams["id"]) => [{ url: '/api/task-status/:id/', params: {id:id} }] as const

export type TaskStatusRetrieveQueryKey = ReturnType<typeof taskStatusRetrieveQueryKey>

/**
 * {@link /api/task-status/:id/}
 */
export async function taskStatusRetrieve(id: TaskStatusRetrievePathParams["id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<TaskStatusRetrieveQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/api/task-status/${id}/`, ... requestConfig })  
  return res.data
}

export function taskStatusRetrieveQueryOptions(id: TaskStatusRetrievePathParams["id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = taskStatusRetrieveQueryKey(id)
  return queryOptions<TaskStatusRetrieveQueryResponse, ResponseErrorConfig<Error>, TaskStatusRetrieveQueryResponse, typeof queryKey>({
   enabled: !!(id),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return taskStatusRetrieve(id, config)
   },
  })
}

/**
 * {@link /api/task-status/:id/}
 */
export function useTaskStatusRetrieve<TData = TaskStatusRetrieveQueryResponse, TQueryData = TaskStatusRetrieveQueryResponse, TQueryKey extends QueryKey = TaskStatusRetrieveQueryKey>(id: TaskStatusRetrievePathParams["id"], options: 
{
  query?: Partial<QueryObserverOptions<TaskStatusRetrieveQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? taskStatusRetrieveQueryKey(id)

  const query = useQuery({
   ...taskStatusRetrieveQueryOptions(id, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}