/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/api/client.ts";
import type { TaskStatusListQueryResponse } from "../../types/TaskStatusList.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/api/client.ts";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const taskStatusListSuspenseQueryKey = () => [{ url: '/api/task-status/' }] as const

export type TaskStatusListSuspenseQueryKey = ReturnType<typeof taskStatusListSuspenseQueryKey>

/**
 * {@link /api/task-status/}
 */
export async function taskStatusListSuspense(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<TaskStatusListQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/api/task-status/`, ... requestConfig })  
  return res.data
}

export function taskStatusListSuspenseQueryOptions(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = taskStatusListSuspenseQueryKey()
  return queryOptions<TaskStatusListQueryResponse, ResponseErrorConfig<Error>, TaskStatusListQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return taskStatusListSuspense(config)
   },
  })
}

/**
 * {@link /api/task-status/}
 */
export function useTaskStatusListSuspense<TData = TaskStatusListQueryResponse, TQueryKey extends QueryKey = TaskStatusListSuspenseQueryKey>(options: 
{
  query?: Partial<UseSuspenseQueryOptions<TaskStatusListQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? taskStatusListSuspenseQueryKey()

  const query = useSuspenseQuery({
   ...taskStatusListSuspenseQueryOptions(config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}