/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/api/client.ts";
import type { TaskStatusUpdateMutationRequest, TaskStatusUpdateMutationResponse, TaskStatusUpdatePathParams } from "../../types/TaskStatusUpdate.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/api/client.ts";
import type { UseMutationOptions, QueryClient } from "@tanstack/react-query";
import { useMutation } from "@tanstack/react-query";

export const taskStatusUpdateMutationKey = () => [{ url: '/api/task-status/:id/' }] as const

export type TaskStatusUpdateMutationKey = ReturnType<typeof taskStatusUpdateMutationKey>

/**
 * {@link /api/task-status/:id/}
 */
export async function taskStatusUpdate(id: TaskStatusUpdatePathParams["id"], data: TaskStatusUpdateMutationRequest, config: Partial<RequestConfig<TaskStatusUpdateMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<TaskStatusUpdateMutationResponse, ResponseErrorConfig<Error>, TaskStatusUpdateMutationRequest>({ method : "PUT", url : `/api/task-status/${id}/`, data : requestData, ... requestConfig })  
  return res.data
}

/**
 * {@link /api/task-status/:id/}
 */
export function useTaskStatusUpdate<TContext>(options: 
{
  mutation?: UseMutationOptions<TaskStatusUpdateMutationResponse, ResponseErrorConfig<Error>, {id: TaskStatusUpdatePathParams["id"], data: TaskStatusUpdateMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<TaskStatusUpdateMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? taskStatusUpdateMutationKey()

  return useMutation<TaskStatusUpdateMutationResponse, ResponseErrorConfig<Error>, {id: TaskStatusUpdatePathParams["id"], data: TaskStatusUpdateMutationRequest}, TContext>({
    mutationFn: async({ id, data }) => {
      return taskStatusUpdate(id, data, config)
    },
    mutationKey,
    ...mutationOptions
  }, queryClient)
}