/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/api/client.ts";
import type { ProjectsListQueryResponse, ProjectsListQueryParams } from "../../types/ProjectsList.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/api/client.ts";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const projectsListSuspenseQueryKey = (params?: ProjectsListQueryParams) => [{ url: '/api/projects/' }, ...(params ? [params] : [])] as const

export type ProjectsListSuspenseQueryKey = ReturnType<typeof projectsListSuspenseQueryKey>

/**
 * {@link /api/projects/}
 */
export async function projectsListSuspense(params?: ProjectsListQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<ProjectsListQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/api/projects/`, params, ... requestConfig })  
  return res.data
}

export function projectsListSuspenseQueryOptions(params?: ProjectsListQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = projectsListSuspenseQueryKey(params)
  return queryOptions<ProjectsListQueryResponse, ResponseErrorConfig<Error>, ProjectsListQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return projectsListSuspense(params, config)
   },
  })
}

/**
 * {@link /api/projects/}
 */
export function useProjectsListSuspense<TData = ProjectsListQueryResponse, TQueryKey extends QueryKey = ProjectsListSuspenseQueryKey>(params?: ProjectsListQueryParams, options: 
{
  query?: Partial<UseSuspenseQueryOptions<ProjectsListQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? projectsListSuspenseQueryKey(params)

  const query = useSuspenseQuery({
   ...projectsListSuspenseQueryOptions(params, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}