/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/api/client.ts";
import type { ProjectsCreateMutationRequest, ProjectsCreateMutationResponse } from "../../types/ProjectsCreate.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/api/client.ts";
import type { UseMutationOptions, QueryClient } from "@tanstack/react-query";
import { useMutation } from "@tanstack/react-query";

export const projectsCreateMutationKey = () => [{ url: '/api/projects/' }] as const

export type ProjectsCreateMutationKey = ReturnType<typeof projectsCreateMutationKey>

/**
 * {@link /api/projects/}
 */
export async function projectsCreate(data: ProjectsCreateMutationRequest, config: Partial<RequestConfig<ProjectsCreateMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<ProjectsCreateMutationResponse, ResponseErrorConfig<Error>, ProjectsCreateMutationRequest>({ method : "POST", url : `/api/projects/`, data : requestData, ... requestConfig })  
  return res.data
}

/**
 * {@link /api/projects/}
 */
export function useProjectsCreate<TContext>(options: 
{
  mutation?: UseMutationOptions<ProjectsCreateMutationResponse, ResponseErrorConfig<Error>, {data: ProjectsCreateMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<ProjectsCreateMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? projectsCreateMutationKey()

  return useMutation<ProjectsCreateMutationResponse, ResponseErrorConfig<Error>, {data: ProjectsCreateMutationRequest}, TContext>({
    mutationFn: async({ data }) => {
      return projectsCreate(data, config)
    },
    mutationKey,
    ...mutationOptions
  }, queryClient)
}