/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/api/client.ts";
import type { ProjectsProjectWiseProjectMembersListQueryResponse, ProjectsProjectWiseProjectMembersListPathParams, ProjectsProjectWiseProjectMembersListQueryParams } from "../../types/ProjectsProjectWiseProjectMembersList.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/api/client.ts";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const projectsProjectWiseProjectMembersListSuspenseQueryKey = (parent_lookup_project: ProjectsProjectWiseProjectMembersListPathParams["parent_lookup_project"], params?: ProjectsProjectWiseProjectMembersListQueryParams) => [{ url: '/api/projects/:parent_lookup_project/project-wise-project-members/', params: {parent_lookup_project:parent_lookup_project} }, ...(params ? [params] : [])] as const

export type ProjectsProjectWiseProjectMembersListSuspenseQueryKey = ReturnType<typeof projectsProjectWiseProjectMembersListSuspenseQueryKey>

/**
 * {@link /api/projects/:parent_lookup_project/project-wise-project-members/}
 */
export async function projectsProjectWiseProjectMembersListSuspense(parent_lookup_project: ProjectsProjectWiseProjectMembersListPathParams["parent_lookup_project"], params?: ProjectsProjectWiseProjectMembersListQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<ProjectsProjectWiseProjectMembersListQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/api/projects/${parent_lookup_project}/project-wise-project-members/`, params, ... requestConfig })  
  return res.data
}

export function projectsProjectWiseProjectMembersListSuspenseQueryOptions(parent_lookup_project: ProjectsProjectWiseProjectMembersListPathParams["parent_lookup_project"], params?: ProjectsProjectWiseProjectMembersListQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = projectsProjectWiseProjectMembersListSuspenseQueryKey(parent_lookup_project, params)
  return queryOptions<ProjectsProjectWiseProjectMembersListQueryResponse, ResponseErrorConfig<Error>, ProjectsProjectWiseProjectMembersListQueryResponse, typeof queryKey>({
   enabled: !!(parent_lookup_project),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return projectsProjectWiseProjectMembersListSuspense(parent_lookup_project, params, config)
   },
  })
}

/**
 * {@link /api/projects/:parent_lookup_project/project-wise-project-members/}
 */
export function useProjectsProjectWiseProjectMembersListSuspense<TData = ProjectsProjectWiseProjectMembersListQueryResponse, TQueryKey extends QueryKey = ProjectsProjectWiseProjectMembersListSuspenseQueryKey>(parent_lookup_project: ProjectsProjectWiseProjectMembersListPathParams["parent_lookup_project"], params?: ProjectsProjectWiseProjectMembersListQueryParams, options: 
{
  query?: Partial<UseSuspenseQueryOptions<ProjectsProjectWiseProjectMembersListQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? projectsProjectWiseProjectMembersListSuspenseQueryKey(parent_lookup_project, params)

  const query = useSuspenseQuery({
   ...projectsProjectWiseProjectMembersListSuspenseQueryOptions(parent_lookup_project, params, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}