/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/api/client.ts";
import type { ProjectsTasksSearchRetrieveQueryResponse, ProjectsTasksSearchRetrievePathParams } from "../../types/ProjectsTasksSearchRetrieve.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/api/client.ts";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const projectsTasksSearchRetrieveSuspenseQueryKey = (parent_lookup_project: ProjectsTasksSearchRetrievePathParams["parent_lookup_project"]) => [{ url: '/api/projects/:parent_lookup_project/tasks/search/', params: {parent_lookup_project:parent_lookup_project} }] as const

export type ProjectsTasksSearchRetrieveSuspenseQueryKey = ReturnType<typeof projectsTasksSearchRetrieveSuspenseQueryKey>

/**
 * {@link /api/projects/:parent_lookup_project/tasks/search/}
 */
export async function projectsTasksSearchRetrieveSuspense(parent_lookup_project: ProjectsTasksSearchRetrievePathParams["parent_lookup_project"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<ProjectsTasksSearchRetrieveQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/api/projects/${parent_lookup_project}/tasks/search/`, ... requestConfig })  
  return res.data
}

export function projectsTasksSearchRetrieveSuspenseQueryOptions(parent_lookup_project: ProjectsTasksSearchRetrievePathParams["parent_lookup_project"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = projectsTasksSearchRetrieveSuspenseQueryKey(parent_lookup_project)
  return queryOptions<ProjectsTasksSearchRetrieveQueryResponse, ResponseErrorConfig<Error>, ProjectsTasksSearchRetrieveQueryResponse, typeof queryKey>({
   enabled: !!(parent_lookup_project),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return projectsTasksSearchRetrieveSuspense(parent_lookup_project, config)
   },
  })
}

/**
 * {@link /api/projects/:parent_lookup_project/tasks/search/}
 */
export function useProjectsTasksSearchRetrieveSuspense<TData = ProjectsTasksSearchRetrieveQueryResponse, TQueryKey extends QueryKey = ProjectsTasksSearchRetrieveSuspenseQueryKey>(parent_lookup_project: ProjectsTasksSearchRetrievePathParams["parent_lookup_project"], options: 
{
  query?: Partial<UseSuspenseQueryOptions<ProjectsTasksSearchRetrieveQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? projectsTasksSearchRetrieveSuspenseQueryKey(parent_lookup_project)

  const query = useSuspenseQuery({
   ...projectsTasksSearchRetrieveSuspenseQueryOptions(parent_lookup_project, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}