/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/api/client.ts";
import type { ProjectsPartialUpdateMutationRequest, ProjectsPartialUpdateMutationResponse, ProjectsPartialUpdatePathParams } from "../../types/ProjectsPartialUpdate.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/api/client.ts";
import type { UseMutationOptions, QueryClient } from "@tanstack/react-query";
import { useMutation } from "@tanstack/react-query";

export const projectsPartialUpdateMutationKey = () => [{ url: '/api/projects/:id/' }] as const

export type ProjectsPartialUpdateMutationKey = ReturnType<typeof projectsPartialUpdateMutationKey>

/**
 * {@link /api/projects/:id/}
 */
export async function projectsPartialUpdate(id: ProjectsPartialUpdatePathParams["id"], data?: ProjectsPartialUpdateMutationRequest, config: Partial<RequestConfig<ProjectsPartialUpdateMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<ProjectsPartialUpdateMutationResponse, ResponseErrorConfig<Error>, ProjectsPartialUpdateMutationRequest>({ method : "PATCH", url : `/api/projects/${id}/`, data : requestData, ... requestConfig })  
  return res.data
}

/**
 * {@link /api/projects/:id/}
 */
export function useProjectsPartialUpdate<TContext>(options: 
{
  mutation?: UseMutationOptions<ProjectsPartialUpdateMutationResponse, ResponseErrorConfig<Error>, {id: ProjectsPartialUpdatePathParams["id"], data?: ProjectsPartialUpdateMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<ProjectsPartialUpdateMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? projectsPartialUpdateMutationKey()

  return useMutation<ProjectsPartialUpdateMutationResponse, ResponseErrorConfig<Error>, {id: ProjectsPartialUpdatePathParams["id"], data?: ProjectsPartialUpdateMutationRequest}, TContext>({
    mutationFn: async({ id, data }) => {
      return projectsPartialUpdate(id, data, config)
    },
    mutationKey,
    ...mutationOptions
  }, queryClient)
}