/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/api/client.ts";
import type { ProjectsTasksSearchRetrieveQueryResponse, ProjectsTasksSearchRetrievePathParams } from "../../types/ProjectsTasksSearchRetrieve.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/api/client.ts";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const projectsTasksSearchRetrieveQueryKey = (parent_lookup_project: ProjectsTasksSearchRetrievePathParams["parent_lookup_project"]) => [{ url: '/api/projects/:parent_lookup_project/tasks/search/', params: {parent_lookup_project:parent_lookup_project} }] as const

export type ProjectsTasksSearchRetrieveQueryKey = ReturnType<typeof projectsTasksSearchRetrieveQueryKey>

/**
 * {@link /api/projects/:parent_lookup_project/tasks/search/}
 */
export async function projectsTasksSearchRetrieve(parent_lookup_project: ProjectsTasksSearchRetrievePathParams["parent_lookup_project"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<ProjectsTasksSearchRetrieveQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/api/projects/${parent_lookup_project}/tasks/search/`, ... requestConfig })  
  return res.data
}

export function projectsTasksSearchRetrieveQueryOptions(parent_lookup_project: ProjectsTasksSearchRetrievePathParams["parent_lookup_project"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = projectsTasksSearchRetrieveQueryKey(parent_lookup_project)
  return queryOptions<ProjectsTasksSearchRetrieveQueryResponse, ResponseErrorConfig<Error>, ProjectsTasksSearchRetrieveQueryResponse, typeof queryKey>({
   enabled: !!(parent_lookup_project),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return projectsTasksSearchRetrieve(parent_lookup_project, config)
   },
  })
}

/**
 * {@link /api/projects/:parent_lookup_project/tasks/search/}
 */
export function useProjectsTasksSearchRetrieve<TData = ProjectsTasksSearchRetrieveQueryResponse, TQueryData = ProjectsTasksSearchRetrieveQueryResponse, TQueryKey extends QueryKey = ProjectsTasksSearchRetrieveQueryKey>(parent_lookup_project: ProjectsTasksSearchRetrievePathParams["parent_lookup_project"], options: 
{
  query?: Partial<QueryObserverOptions<ProjectsTasksSearchRetrieveQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? projectsTasksSearchRetrieveQueryKey(parent_lookup_project)

  const query = useQuery({
   ...projectsTasksSearchRetrieveQueryOptions(parent_lookup_project, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}