/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/api/client.ts";
import type { ProjectsRetrieveQueryResponse, ProjectsRetrievePathParams } from "../../types/ProjectsRetrieve.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/api/client.ts";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const projectsRetrieveSuspenseQueryKey = (id: ProjectsRetrievePathParams["id"]) => [{ url: '/api/projects/:id/', params: {id:id} }] as const

export type ProjectsRetrieveSuspenseQueryKey = ReturnType<typeof projectsRetrieveSuspenseQueryKey>

/**
 * {@link /api/projects/:id/}
 */
export async function projectsRetrieveSuspense(id: ProjectsRetrievePathParams["id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<ProjectsRetrieveQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/api/projects/${id}/`, ... requestConfig })  
  return res.data
}

export function projectsRetrieveSuspenseQueryOptions(id: ProjectsRetrievePathParams["id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = projectsRetrieveSuspenseQueryKey(id)
  return queryOptions<ProjectsRetrieveQueryResponse, ResponseErrorConfig<Error>, ProjectsRetrieveQueryResponse, typeof queryKey>({
   enabled: !!(id),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return projectsRetrieveSuspense(id, config)
   },
  })
}

/**
 * {@link /api/projects/:id/}
 */
export function useProjectsRetrieveSuspense<TData = ProjectsRetrieveQueryResponse, TQueryKey extends QueryKey = ProjectsRetrieveSuspenseQueryKey>(id: ProjectsRetrievePathParams["id"], options: 
{
  query?: Partial<UseSuspenseQueryOptions<ProjectsRetrieveQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? projectsRetrieveSuspenseQueryKey(id)

  const query = useSuspenseQuery({
   ...projectsRetrieveSuspenseQueryOptions(id, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}