/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/api/client.ts";
import type { ProjectsProjectWiseProjectMembersListQueryResponse, ProjectsProjectWiseProjectMembersListPathParams, ProjectsProjectWiseProjectMembersListQueryParams } from "../../types/ProjectsProjectWiseProjectMembersList.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/api/client.ts";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const projectsProjectWiseProjectMembersListQueryKey = (parent_lookup_project: ProjectsProjectWiseProjectMembersListPathParams["parent_lookup_project"], params?: ProjectsProjectWiseProjectMembersListQueryParams) => [{ url: '/api/projects/:parent_lookup_project/project-wise-project-members/', params: {parent_lookup_project:parent_lookup_project} }, ...(params ? [params] : [])] as const

export type ProjectsProjectWiseProjectMembersListQueryKey = ReturnType<typeof projectsProjectWiseProjectMembersListQueryKey>

/**
 * {@link /api/projects/:parent_lookup_project/project-wise-project-members/}
 */
export async function projectsProjectWiseProjectMembersList(parent_lookup_project: ProjectsProjectWiseProjectMembersListPathParams["parent_lookup_project"], params?: ProjectsProjectWiseProjectMembersListQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<ProjectsProjectWiseProjectMembersListQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/api/projects/${parent_lookup_project}/project-wise-project-members/`, params, ... requestConfig })  
  return res.data
}

export function projectsProjectWiseProjectMembersListQueryOptions(parent_lookup_project: ProjectsProjectWiseProjectMembersListPathParams["parent_lookup_project"], params?: ProjectsProjectWiseProjectMembersListQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = projectsProjectWiseProjectMembersListQueryKey(parent_lookup_project, params)
  return queryOptions<ProjectsProjectWiseProjectMembersListQueryResponse, ResponseErrorConfig<Error>, ProjectsProjectWiseProjectMembersListQueryResponse, typeof queryKey>({
   enabled: !!(parent_lookup_project),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return projectsProjectWiseProjectMembersList(parent_lookup_project, params, config)
   },
  })
}

/**
 * {@link /api/projects/:parent_lookup_project/project-wise-project-members/}
 */
export function useProjectsProjectWiseProjectMembersList<TData = ProjectsProjectWiseProjectMembersListQueryResponse, TQueryData = ProjectsProjectWiseProjectMembersListQueryResponse, TQueryKey extends QueryKey = ProjectsProjectWiseProjectMembersListQueryKey>(parent_lookup_project: ProjectsProjectWiseProjectMembersListPathParams["parent_lookup_project"], params?: ProjectsProjectWiseProjectMembersListQueryParams, options: 
{
  query?: Partial<QueryObserverOptions<ProjectsProjectWiseProjectMembersListQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? projectsProjectWiseProjectMembersListQueryKey(parent_lookup_project, params)

  const query = useQuery({
   ...projectsProjectWiseProjectMembersListQueryOptions(parent_lookup_project, params, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}