/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/api/client.ts";
import type { ProjectsRetrieveQueryResponse, ProjectsRetrievePathParams } from "../../types/ProjectsRetrieve.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/api/client.ts";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const projectsRetrieveQueryKey = (id: ProjectsRetrievePathParams["id"]) => [{ url: '/api/projects/:id/', params: {id:id} }] as const

export type ProjectsRetrieveQueryKey = ReturnType<typeof projectsRetrieveQueryKey>

/**
 * {@link /api/projects/:id/}
 */
export async function projectsRetrieve(id: ProjectsRetrievePathParams["id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<ProjectsRetrieveQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/api/projects/${id}/`, ... requestConfig })  
  return res.data
}

export function projectsRetrieveQueryOptions(id: ProjectsRetrievePathParams["id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = projectsRetrieveQueryKey(id)
  return queryOptions<ProjectsRetrieveQueryResponse, ResponseErrorConfig<Error>, ProjectsRetrieveQueryResponse, typeof queryKey>({
   enabled: !!(id),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return projectsRetrieve(id, config)
   },
  })
}

/**
 * {@link /api/projects/:id/}
 */
export function useProjectsRetrieve<TData = ProjectsRetrieveQueryResponse, TQueryData = ProjectsRetrieveQueryResponse, TQueryKey extends QueryKey = ProjectsRetrieveQueryKey>(id: ProjectsRetrievePathParams["id"], options: 
{
  query?: Partial<QueryObserverOptions<ProjectsRetrieveQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? projectsRetrieveQueryKey(id)

  const query = useQuery({
   ...projectsRetrieveQueryOptions(id, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}