/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/api/client.ts";
import type { ProjectsSearchRetrieveQueryResponse } from "../../types/ProjectsSearchRetrieve.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/api/client.ts";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const projectsSearchRetrieveSuspenseQueryKey = () => [{ url: '/api/projects/search/' }] as const

export type ProjectsSearchRetrieveSuspenseQueryKey = ReturnType<typeof projectsSearchRetrieveSuspenseQueryKey>

/**
 * {@link /api/projects/search/}
 */
export async function projectsSearchRetrieveSuspense(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<ProjectsSearchRetrieveQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/api/projects/search/`, ... requestConfig })  
  return res.data
}

export function projectsSearchRetrieveSuspenseQueryOptions(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = projectsSearchRetrieveSuspenseQueryKey()
  return queryOptions<ProjectsSearchRetrieveQueryResponse, ResponseErrorConfig<Error>, ProjectsSearchRetrieveQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return projectsSearchRetrieveSuspense(config)
   },
  })
}

/**
 * {@link /api/projects/search/}
 */
export function useProjectsSearchRetrieveSuspense<TData = ProjectsSearchRetrieveQueryResponse, TQueryKey extends QueryKey = ProjectsSearchRetrieveSuspenseQueryKey>(options: 
{
  query?: Partial<UseSuspenseQueryOptions<ProjectsSearchRetrieveQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? projectsSearchRetrieveSuspenseQueryKey()

  const query = useSuspenseQuery({
   ...projectsSearchRetrieveSuspenseQueryOptions(config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}