/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/api/client.ts";
import type { ProjectsSearchRetrieveQueryResponse } from "../../types/ProjectsSearchRetrieve.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/api/client.ts";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const projectsSearchRetrieveQueryKey = () => [{ url: '/api/projects/search/' }] as const

export type ProjectsSearchRetrieveQueryKey = ReturnType<typeof projectsSearchRetrieveQueryKey>

/**
 * {@link /api/projects/search/}
 */
export async function projectsSearchRetrieve(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<ProjectsSearchRetrieveQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/api/projects/search/`, ... requestConfig })  
  return res.data
}

export function projectsSearchRetrieveQueryOptions(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = projectsSearchRetrieveQueryKey()
  return queryOptions<ProjectsSearchRetrieveQueryResponse, ResponseErrorConfig<Error>, ProjectsSearchRetrieveQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return projectsSearchRetrieve(config)
   },
  })
}

/**
 * {@link /api/projects/search/}
 */
export function useProjectsSearchRetrieve<TData = ProjectsSearchRetrieveQueryResponse, TQueryData = ProjectsSearchRetrieveQueryResponse, TQueryKey extends QueryKey = ProjectsSearchRetrieveQueryKey>(options: 
{
  query?: Partial<QueryObserverOptions<ProjectsSearchRetrieveQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? projectsSearchRetrieveQueryKey()

  const query = useQuery({
   ...projectsSearchRetrieveQueryOptions(config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}