/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/api/client.ts";
import type { ProjectsListQueryResponse, ProjectsListQueryParams } from "../../types/ProjectsList.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/api/client.ts";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const projectsListQueryKey = (params?: ProjectsListQueryParams) => [{ url: '/api/projects/' }, ...(params ? [params] : [])] as const

export type ProjectsListQueryKey = ReturnType<typeof projectsListQueryKey>

/**
 * {@link /api/projects/}
 */
export async function projectsList(params?: ProjectsListQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<ProjectsListQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/api/projects/`, params, ... requestConfig })  
  return res.data
}

export function projectsListQueryOptions(params?: ProjectsListQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = projectsListQueryKey(params)
  return queryOptions<ProjectsListQueryResponse, ResponseErrorConfig<Error>, ProjectsListQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return projectsList(params, config)
   },
  })
}

/**
 * {@link /api/projects/}
 */
export function useProjectsList<TData = ProjectsListQueryResponse, TQueryData = ProjectsListQueryResponse, TQueryKey extends QueryKey = ProjectsListQueryKey>(params?: ProjectsListQueryParams, options: 
{
  query?: Partial<QueryObserverOptions<ProjectsListQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? projectsListQueryKey(params)

  const query = useQuery({
   ...projectsListQueryOptions(params, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}