/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/api/client.ts";
import type { ProjectsUpdateMutationRequest, ProjectsUpdateMutationResponse, ProjectsUpdatePathParams } from "../../types/ProjectsUpdate.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/api/client.ts";
import type { UseMutationOptions, QueryClient } from "@tanstack/react-query";
import { useMutation } from "@tanstack/react-query";

export const projectsUpdateMutationKey = () => [{ url: '/api/projects/:id/' }] as const

export type ProjectsUpdateMutationKey = ReturnType<typeof projectsUpdateMutationKey>

/**
 * {@link /api/projects/:id/}
 */
export async function projectsUpdate(id: ProjectsUpdatePathParams["id"], data: ProjectsUpdateMutationRequest, config: Partial<RequestConfig<ProjectsUpdateMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<ProjectsUpdateMutationResponse, ResponseErrorConfig<Error>, ProjectsUpdateMutationRequest>({ method : "PUT", url : `/api/projects/${id}/`, data : requestData, ... requestConfig })  
  return res.data
}

/**
 * {@link /api/projects/:id/}
 */
export function useProjectsUpdate<TContext>(options: 
{
  mutation?: UseMutationOptions<ProjectsUpdateMutationResponse, ResponseErrorConfig<Error>, {id: ProjectsUpdatePathParams["id"], data: ProjectsUpdateMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<ProjectsUpdateMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? projectsUpdateMutationKey()

  return useMutation<ProjectsUpdateMutationResponse, ResponseErrorConfig<Error>, {id: ProjectsUpdatePathParams["id"], data: ProjectsUpdateMutationRequest}, TContext>({
    mutationFn: async({ id, data }) => {
      return projectsUpdate(id, data, config)
    },
    mutationKey,
    ...mutationOptions
  }, queryClient)
}