/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/api/client.ts";
import type { ProjectsDestroyMutationResponse, ProjectsDestroyPathParams } from "../../types/ProjectsDestroy.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/api/client.ts";
import type { UseMutationOptions, QueryClient } from "@tanstack/react-query";
import { useMutation } from "@tanstack/react-query";

export const projectsDestroyMutationKey = () => [{ url: '/api/projects/:id/' }] as const

export type ProjectsDestroyMutationKey = ReturnType<typeof projectsDestroyMutationKey>

/**
 * {@link /api/projects/:id/}
 */
export async function projectsDestroy(id: ProjectsDestroyPathParams["id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<ProjectsDestroyMutationResponse, ResponseErrorConfig<Error>, unknown>({ method : "DELETE", url : `/api/projects/${id}/`, ... requestConfig })  
  return res.data
}

/**
 * {@link /api/projects/:id/}
 */
export function useProjectsDestroy<TContext>(options: 
{
  mutation?: UseMutationOptions<ProjectsDestroyMutationResponse, ResponseErrorConfig<Error>, {id: ProjectsDestroyPathParams["id"]}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? projectsDestroyMutationKey()

  return useMutation<ProjectsDestroyMutationResponse, ResponseErrorConfig<Error>, {id: ProjectsDestroyPathParams["id"]}, TContext>({
    mutationFn: async({ id }) => {
      return projectsDestroy(id, config)
    },
    mutationKey,
    ...mutationOptions
  }, queryClient)
}