/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/api/client.ts";
import type { TenantsGetTenantThemeRetrieveQueryResponse, TenantsGetTenantThemeRetrieve404 } from "../../types/TenantsGetTenantThemeRetrieve.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/api/client.ts";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const tenantsGetTenantThemeRetrieveSuspenseQueryKey = () => [{ url: '/api/tenants/get-tenant-theme/' }] as const

export type TenantsGetTenantThemeRetrieveSuspenseQueryKey = ReturnType<typeof tenantsGetTenantThemeRetrieveSuspenseQueryKey>

/**
 * {@link /api/tenants/get-tenant-theme/}
 */
export async function tenantsGetTenantThemeRetrieveSuspense(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<TenantsGetTenantThemeRetrieveQueryResponse, ResponseErrorConfig<TenantsGetTenantThemeRetrieve404>, unknown>({ method : "GET", url : `/api/tenants/get-tenant-theme/`, ... requestConfig })  
  return res.data
}

export function tenantsGetTenantThemeRetrieveSuspenseQueryOptions(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = tenantsGetTenantThemeRetrieveSuspenseQueryKey()
  return queryOptions<TenantsGetTenantThemeRetrieveQueryResponse, ResponseErrorConfig<TenantsGetTenantThemeRetrieve404>, TenantsGetTenantThemeRetrieveQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return tenantsGetTenantThemeRetrieveSuspense(config)
   },
  })
}

/**
 * {@link /api/tenants/get-tenant-theme/}
 */
export function useTenantsGetTenantThemeRetrieveSuspense<TData = TenantsGetTenantThemeRetrieveQueryResponse, TQueryKey extends QueryKey = TenantsGetTenantThemeRetrieveSuspenseQueryKey>(options: 
{
  query?: Partial<UseSuspenseQueryOptions<TenantsGetTenantThemeRetrieveQueryResponse, ResponseErrorConfig<TenantsGetTenantThemeRetrieve404>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? tenantsGetTenantThemeRetrieveSuspenseQueryKey()

  const query = useSuspenseQuery({
   ...tenantsGetTenantThemeRetrieveSuspenseQueryOptions(config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<TenantsGetTenantThemeRetrieve404>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}