/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/api/client.ts";
import type { AuthPasswordResetConfirmCreateMutationRequest, AuthPasswordResetConfirmCreateMutationResponse } from "../../types/AuthPasswordResetConfirmCreate.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/api/client.ts";
import type { UseMutationOptions, QueryClient } from "@tanstack/react-query";
import { useMutation } from "@tanstack/react-query";

export const authPasswordResetConfirmCreateMutationKey = () => [{ url: '/api/auth/password/reset/confirm/' }] as const

export type AuthPasswordResetConfirmCreateMutationKey = ReturnType<typeof authPasswordResetConfirmCreateMutationKey>

/**
 * @description Password reset e-mail link is confirmed, thereforethis resets the user's password.Accepts the following POST parameters: token, uid,    new_password1, new_password2Returns the success/fail message.
 * {@link /api/auth/password/reset/confirm/}
 */
export async function authPasswordResetConfirmCreate(data: AuthPasswordResetConfirmCreateMutationRequest, config: Partial<RequestConfig<AuthPasswordResetConfirmCreateMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<AuthPasswordResetConfirmCreateMutationResponse, ResponseErrorConfig<Error>, AuthPasswordResetConfirmCreateMutationRequest>({ method : "POST", url : `/api/auth/password/reset/confirm/`, data : requestData, ... requestConfig })  
  return res.data
}

/**
 * @description Password reset e-mail link is confirmed, thereforethis resets the user's password.Accepts the following POST parameters: token, uid,    new_password1, new_password2Returns the success/fail message.
 * {@link /api/auth/password/reset/confirm/}
 */
export function useAuthPasswordResetConfirmCreate<TContext>(options: 
{
  mutation?: UseMutationOptions<AuthPasswordResetConfirmCreateMutationResponse, ResponseErrorConfig<Error>, {data: AuthPasswordResetConfirmCreateMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<AuthPasswordResetConfirmCreateMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? authPasswordResetConfirmCreateMutationKey()

  return useMutation<AuthPasswordResetConfirmCreateMutationResponse, ResponseErrorConfig<Error>, {data: AuthPasswordResetConfirmCreateMutationRequest}, TContext>({
    mutationFn: async({ data }) => {
      return authPasswordResetConfirmCreate(data, config)
    },
    mutationKey,
    ...mutationOptions
  }, queryClient)
}