/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/api/client.ts";
import type { AuthPasswordResetConfirmCreate2MutationRequest, AuthPasswordResetConfirmCreate2MutationResponse, AuthPasswordResetConfirmCreate2PathParams } from "../../types/AuthPasswordResetConfirmCreate2.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/api/client.ts";
import type { UseMutationOptions, QueryClient } from "@tanstack/react-query";
import { useMutation } from "@tanstack/react-query";

export const authPasswordResetConfirmCreate2MutationKey = () => [{ url: '/api/auth/password/reset/confirm/:uidb64/:token/' }] as const

export type AuthPasswordResetConfirmCreate2MutationKey = ReturnType<typeof authPasswordResetConfirmCreate2MutationKey>

/**
 * @description Password reset e-mail link is confirmed, thereforethis resets the user's password.Accepts the following POST parameters: token, uid,    new_password1, new_password2Returns the success/fail message.
 * {@link /api/auth/password/reset/confirm/:uidb64/:token/}
 */
export async function authPasswordResetConfirmCreate2(token: AuthPasswordResetConfirmCreate2PathParams["token"], uidb64: AuthPasswordResetConfirmCreate2PathParams["uidb64"], data: AuthPasswordResetConfirmCreate2MutationRequest, config: Partial<RequestConfig<AuthPasswordResetConfirmCreate2MutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<AuthPasswordResetConfirmCreate2MutationResponse, ResponseErrorConfig<Error>, AuthPasswordResetConfirmCreate2MutationRequest>({ method : "POST", url : `/api/auth/password/reset/confirm/${uidb64}/${token}/`, data : requestData, ... requestConfig })  
  return res.data
}

/**
 * @description Password reset e-mail link is confirmed, thereforethis resets the user's password.Accepts the following POST parameters: token, uid,    new_password1, new_password2Returns the success/fail message.
 * {@link /api/auth/password/reset/confirm/:uidb64/:token/}
 */
export function useAuthPasswordResetConfirmCreate2<TContext>(options: 
{
  mutation?: UseMutationOptions<AuthPasswordResetConfirmCreate2MutationResponse, ResponseErrorConfig<Error>, {token: AuthPasswordResetConfirmCreate2PathParams["token"], uidb64: AuthPasswordResetConfirmCreate2PathParams["uidb64"], data: AuthPasswordResetConfirmCreate2MutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<AuthPasswordResetConfirmCreate2MutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? authPasswordResetConfirmCreate2MutationKey()

  return useMutation<AuthPasswordResetConfirmCreate2MutationResponse, ResponseErrorConfig<Error>, {token: AuthPasswordResetConfirmCreate2PathParams["token"], uidb64: AuthPasswordResetConfirmCreate2PathParams["uidb64"], data: AuthPasswordResetConfirmCreate2MutationRequest}, TContext>({
    mutationFn: async({ token, uidb64, data }) => {
      return authPasswordResetConfirmCreate2(token, uidb64, data, config)
    },
    mutationKey,
    ...mutationOptions
  }, queryClient)
}