/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/api/client.ts";
import type { AuthUserUpdateMutationRequest, AuthUserUpdateMutationResponse } from "../../types/AuthUserUpdate.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/api/client.ts";
import type { UseMutationOptions, QueryClient } from "@tanstack/react-query";
import { useMutation } from "@tanstack/react-query";

export const authUserUpdateMutationKey = () => [{ url: '/api/auth/user/' }] as const

export type AuthUserUpdateMutationKey = ReturnType<typeof authUserUpdateMutationKey>

/**
 * @description Reads and updates UserModel fieldsAccepts GET, PUT, PATCH methods.Default accepted fields: username, first_name, last_nameDefault display fields: pk, username, email, first_name, last_nameRead-only fields: pk, emailReturns UserModel fields.
 * {@link /api/auth/user/}
 */
export async function authUserUpdate(data: AuthUserUpdateMutationRequest, config: Partial<RequestConfig<AuthUserUpdateMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<AuthUserUpdateMutationResponse, ResponseErrorConfig<Error>, AuthUserUpdateMutationRequest>({ method : "PUT", url : `/api/auth/user/`, data : requestData, ... requestConfig })  
  return res.data
}

/**
 * @description Reads and updates UserModel fieldsAccepts GET, PUT, PATCH methods.Default accepted fields: username, first_name, last_nameDefault display fields: pk, username, email, first_name, last_nameRead-only fields: pk, emailReturns UserModel fields.
 * {@link /api/auth/user/}
 */
export function useAuthUserUpdate<TContext>(options: 
{
  mutation?: UseMutationOptions<AuthUserUpdateMutationResponse, ResponseErrorConfig<Error>, {data: AuthUserUpdateMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<AuthUserUpdateMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? authUserUpdateMutationKey()

  return useMutation<AuthUserUpdateMutationResponse, ResponseErrorConfig<Error>, {data: AuthUserUpdateMutationRequest}, TContext>({
    mutationFn: async({ data }) => {
      return authUserUpdate(data, config)
    },
    mutationKey,
    ...mutationOptions
  }, queryClient)
}