/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/api/client.ts";
import type { AuthTokenRefreshCreateMutationRequest, AuthTokenRefreshCreateMutationResponse } from "../../types/AuthTokenRefreshCreate.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/api/client.ts";
import type { UseMutationOptions, QueryClient } from "@tanstack/react-query";
import { useMutation } from "@tanstack/react-query";

export const authTokenRefreshCreateMutationKey = () => [{ url: '/api/auth/token/refresh/' }] as const

export type AuthTokenRefreshCreateMutationKey = ReturnType<typeof authTokenRefreshCreateMutationKey>

/**
 * @description Takes a refresh type JSON web token and returns an access type JSON webtoken if the refresh token is valid.
 * {@link /api/auth/token/refresh/}
 */
export async function authTokenRefreshCreate(data: AuthTokenRefreshCreateMutationRequest, config: Partial<RequestConfig<AuthTokenRefreshCreateMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<AuthTokenRefreshCreateMutationResponse, ResponseErrorConfig<Error>, AuthTokenRefreshCreateMutationRequest>({ method : "POST", url : `/api/auth/token/refresh/`, data : requestData, ... requestConfig })  
  return res.data
}

/**
 * @description Takes a refresh type JSON web token and returns an access type JSON webtoken if the refresh token is valid.
 * {@link /api/auth/token/refresh/}
 */
export function useAuthTokenRefreshCreate<TContext>(options: 
{
  mutation?: UseMutationOptions<AuthTokenRefreshCreateMutationResponse, ResponseErrorConfig<Error>, {data: AuthTokenRefreshCreateMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<AuthTokenRefreshCreateMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? authTokenRefreshCreateMutationKey()

  return useMutation<AuthTokenRefreshCreateMutationResponse, ResponseErrorConfig<Error>, {data: AuthTokenRefreshCreateMutationRequest}, TContext>({
    mutationFn: async({ data }) => {
      return authTokenRefreshCreate(data, config)
    },
    mutationKey,
    ...mutationOptions
  }, queryClient)
}