/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/api/client.ts";
import type { AuthTokenVerifyCreateMutationRequest, AuthTokenVerifyCreateMutationResponse } from "../../types/AuthTokenVerifyCreate.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/api/client.ts";
import type { UseMutationOptions, QueryClient } from "@tanstack/react-query";
import { useMutation } from "@tanstack/react-query";

export const authTokenVerifyCreateMutationKey = () => [{ url: '/api/auth/token/verify/' }] as const

export type AuthTokenVerifyCreateMutationKey = ReturnType<typeof authTokenVerifyCreateMutationKey>

/**
 * @description Takes a token and indicates if it is valid.  This view provides noinformation about a token's fitness for a particular use.
 * {@link /api/auth/token/verify/}
 */
export async function authTokenVerifyCreate(data: AuthTokenVerifyCreateMutationRequest, config: Partial<RequestConfig<AuthTokenVerifyCreateMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<AuthTokenVerifyCreateMutationResponse, ResponseErrorConfig<Error>, AuthTokenVerifyCreateMutationRequest>({ method : "POST", url : `/api/auth/token/verify/`, data : requestData, ... requestConfig })  
  return res.data
}

/**
 * @description Takes a token and indicates if it is valid.  This view provides noinformation about a token's fitness for a particular use.
 * {@link /api/auth/token/verify/}
 */
export function useAuthTokenVerifyCreate<TContext>(options: 
{
  mutation?: UseMutationOptions<AuthTokenVerifyCreateMutationResponse, ResponseErrorConfig<Error>, {data: AuthTokenVerifyCreateMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<AuthTokenVerifyCreateMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? authTokenVerifyCreateMutationKey()

  return useMutation<AuthTokenVerifyCreateMutationResponse, ResponseErrorConfig<Error>, {data: AuthTokenVerifyCreateMutationRequest}, TContext>({
    mutationFn: async({ data }) => {
      return authTokenVerifyCreate(data, config)
    },
    mutationKey,
    ...mutationOptions
  }, queryClient)
}