/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/api/client.ts";
import type { AuthUserRetrieveQueryResponse } from "../../types/AuthUserRetrieve.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/api/client.ts";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const authUserRetrieveSuspenseQueryKey = () => [{ url: '/api/auth/user/' }] as const

export type AuthUserRetrieveSuspenseQueryKey = ReturnType<typeof authUserRetrieveSuspenseQueryKey>

/**
 * @description Reads and updates UserModel fieldsAccepts GET, PUT, PATCH methods.Default accepted fields: username, first_name, last_nameDefault display fields: pk, username, email, first_name, last_nameRead-only fields: pk, emailReturns UserModel fields.
 * {@link /api/auth/user/}
 */
export async function authUserRetrieveSuspense(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<AuthUserRetrieveQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/api/auth/user/`, ... requestConfig })  
  return res.data
}

export function authUserRetrieveSuspenseQueryOptions(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = authUserRetrieveSuspenseQueryKey()
  return queryOptions<AuthUserRetrieveQueryResponse, ResponseErrorConfig<Error>, AuthUserRetrieveQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return authUserRetrieveSuspense(config)
   },
  })
}

/**
 * @description Reads and updates UserModel fieldsAccepts GET, PUT, PATCH methods.Default accepted fields: username, first_name, last_nameDefault display fields: pk, username, email, first_name, last_nameRead-only fields: pk, emailReturns UserModel fields.
 * {@link /api/auth/user/}
 */
export function useAuthUserRetrieveSuspense<TData = AuthUserRetrieveQueryResponse, TQueryKey extends QueryKey = AuthUserRetrieveSuspenseQueryKey>(options: 
{
  query?: Partial<UseSuspenseQueryOptions<AuthUserRetrieveQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? authUserRetrieveSuspenseQueryKey()

  const query = useSuspenseQuery({
   ...authUserRetrieveSuspenseQueryOptions(config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}