/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/api/client.ts";
import type { TasksCreateMutationRequest, TasksCreateMutationResponse } from "../../types/TasksCreate.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/api/client.ts";
import type { UseMutationOptions, QueryClient } from "@tanstack/react-query";
import { useMutation } from "@tanstack/react-query";

export const tasksCreateMutationKey = () => [{ url: '/api/tasks/' }] as const

export type TasksCreateMutationKey = ReturnType<typeof tasksCreateMutationKey>

/**
 * {@link /api/tasks/}
 */
export async function tasksCreate(data: TasksCreateMutationRequest, config: Partial<RequestConfig<TasksCreateMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<TasksCreateMutationResponse, ResponseErrorConfig<Error>, TasksCreateMutationRequest>({ method : "POST", url : `/api/tasks/`, data : requestData, ... requestConfig })  
  return res.data
}

/**
 * {@link /api/tasks/}
 */
export function useTasksCreate<TContext>(options: 
{
  mutation?: UseMutationOptions<TasksCreateMutationResponse, ResponseErrorConfig<Error>, {data: TasksCreateMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<TasksCreateMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? tasksCreateMutationKey()

  return useMutation<TasksCreateMutationResponse, ResponseErrorConfig<Error>, {data: TasksCreateMutationRequest}, TContext>({
    mutationFn: async({ data }) => {
      return tasksCreate(data, config)
    },
    mutationKey,
    ...mutationOptions
  }, queryClient)
}