/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/api/client.ts";
import type { TasksPartialUpdateMutationRequest, TasksPartialUpdateMutationResponse, TasksPartialUpdatePathParams } from "../../types/TasksPartialUpdate.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/api/client.ts";
import type { UseMutationOptions, QueryClient } from "@tanstack/react-query";
import { useMutation } from "@tanstack/react-query";

export const tasksPartialUpdateMutationKey = () => [{ url: '/api/tasks/:id/' }] as const

export type TasksPartialUpdateMutationKey = ReturnType<typeof tasksPartialUpdateMutationKey>

/**
 * {@link /api/tasks/:id/}
 */
export async function tasksPartialUpdate(id: TasksPartialUpdatePathParams["id"], data?: TasksPartialUpdateMutationRequest, config: Partial<RequestConfig<TasksPartialUpdateMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<TasksPartialUpdateMutationResponse, ResponseErrorConfig<Error>, TasksPartialUpdateMutationRequest>({ method : "PATCH", url : `/api/tasks/${id}/`, data : requestData, ... requestConfig })  
  return res.data
}

/**
 * {@link /api/tasks/:id/}
 */
export function useTasksPartialUpdate<TContext>(options: 
{
  mutation?: UseMutationOptions<TasksPartialUpdateMutationResponse, ResponseErrorConfig<Error>, {id: TasksPartialUpdatePathParams["id"], data?: TasksPartialUpdateMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<TasksPartialUpdateMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? tasksPartialUpdateMutationKey()

  return useMutation<TasksPartialUpdateMutationResponse, ResponseErrorConfig<Error>, {id: TasksPartialUpdatePathParams["id"], data?: TasksPartialUpdateMutationRequest}, TContext>({
    mutationFn: async({ id, data }) => {
      return tasksPartialUpdate(id, data, config)
    },
    mutationKey,
    ...mutationOptions
  }, queryClient)
}