/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/api/client.ts";
import type { TasksRetrieveQueryResponse, TasksRetrievePathParams } from "../../types/TasksRetrieve.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/api/client.ts";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const tasksRetrieveSuspenseQueryKey = (id: TasksRetrievePathParams["id"]) => [{ url: '/api/tasks/:id/', params: {id:id} }] as const

export type TasksRetrieveSuspenseQueryKey = ReturnType<typeof tasksRetrieveSuspenseQueryKey>

/**
 * {@link /api/tasks/:id/}
 */
export async function tasksRetrieveSuspense(id: TasksRetrievePathParams["id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<TasksRetrieveQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/api/tasks/${id}/`, ... requestConfig })  
  return res.data
}

export function tasksRetrieveSuspenseQueryOptions(id: TasksRetrievePathParams["id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = tasksRetrieveSuspenseQueryKey(id)
  return queryOptions<TasksRetrieveQueryResponse, ResponseErrorConfig<Error>, TasksRetrieveQueryResponse, typeof queryKey>({
   enabled: !!(id),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return tasksRetrieveSuspense(id, config)
   },
  })
}

/**
 * {@link /api/tasks/:id/}
 */
export function useTasksRetrieveSuspense<TData = TasksRetrieveQueryResponse, TQueryKey extends QueryKey = TasksRetrieveSuspenseQueryKey>(id: TasksRetrievePathParams["id"], options: 
{
  query?: Partial<UseSuspenseQueryOptions<TasksRetrieveQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? tasksRetrieveSuspenseQueryKey(id)

  const query = useSuspenseQuery({
   ...tasksRetrieveSuspenseQueryOptions(id, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}