/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/api/client.ts";
import type { TasksRetrieveQueryResponse, TasksRetrievePathParams } from "../../types/TasksRetrieve.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/api/client.ts";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const tasksRetrieveQueryKey = (id: TasksRetrievePathParams["id"]) => [{ url: '/api/tasks/:id/', params: {id:id} }] as const

export type TasksRetrieveQueryKey = ReturnType<typeof tasksRetrieveQueryKey>

/**
 * {@link /api/tasks/:id/}
 */
export async function tasksRetrieve(id: TasksRetrievePathParams["id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<TasksRetrieveQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/api/tasks/${id}/`, ... requestConfig })  
  return res.data
}

export function tasksRetrieveQueryOptions(id: TasksRetrievePathParams["id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = tasksRetrieveQueryKey(id)
  return queryOptions<TasksRetrieveQueryResponse, ResponseErrorConfig<Error>, TasksRetrieveQueryResponse, typeof queryKey>({
   enabled: !!(id),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return tasksRetrieve(id, config)
   },
  })
}

/**
 * {@link /api/tasks/:id/}
 */
export function useTasksRetrieve<TData = TasksRetrieveQueryResponse, TQueryData = TasksRetrieveQueryResponse, TQueryKey extends QueryKey = TasksRetrieveQueryKey>(id: TasksRetrievePathParams["id"], options: 
{
  query?: Partial<QueryObserverOptions<TasksRetrieveQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? tasksRetrieveQueryKey(id)

  const query = useQuery({
   ...tasksRetrieveQueryOptions(id, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}