/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PasswordReset } from "./PasswordReset.ts";
import type { RestAuthDetail } from "./RestAuthDetail.ts";

export type AuthPasswordResetCreate200 = RestAuthDetail;

export type AuthPasswordResetCreateMutationRequest = PasswordReset;

export type AuthPasswordResetCreateMutationResponse = AuthPasswordResetCreate200;

export type AuthPasswordResetCreateMutation = {
    Response: AuthPasswordResetCreate200;
    Request: AuthPasswordResetCreateMutationRequest;
    Errors: any;
};