/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { JWT } from "./JWT.ts";
import type { Login } from "./Login.ts";

export type AuthLoginCreate200 = JWT;

export type AuthLoginCreateMutationRequest = Login;

export type AuthLoginCreateMutationResponse = AuthLoginCreate200;

export type AuthLoginCreateMutation = {
    Response: AuthLoginCreate200;
    Request: AuthLoginCreateMutationRequest;
    Errors: any;
};