/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { UserDetails } from "./UserDetails.ts";

export type AuthUserUpdate200 = UserDetails;

export type AuthUserUpdateMutationRequest = Omit<NonNullable<UserDetails>, "pk" | "email" | "first_name" | "last_name">;

export type AuthUserUpdateMutationResponse = AuthUserUpdate200;

export type AuthUserUpdateMutation = {
    Response: AuthUserUpdate200;
    Request: AuthUserUpdateMutationRequest;
    Errors: any;
};