/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { TokenRefresh } from "./TokenRefresh.ts";

export type AuthTokenRefreshCreate200 = Omit<NonNullable<TokenRefresh>, "refresh">;

export type AuthTokenRefreshCreateMutationRequest = Omit<NonNullable<TokenRefresh>, "access">;

export type AuthTokenRefreshCreateMutationResponse = AuthTokenRefreshCreate200;

export type AuthTokenRefreshCreateMutation = {
    Response: AuthTokenRefreshCreate200;
    Request: AuthTokenRefreshCreateMutationRequest;
    Errors: any;
};