/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PasswordResetConfirm } from "./PasswordResetConfirm.ts";
import type { RestAuthDetail } from "./RestAuthDetail.ts";

export type AuthPasswordResetConfirmCreate2PathParams = {
    /**
     * @type string
    */
    token: string;
    /**
     * @type string
    */
    uidb64: string;
};

export type AuthPasswordResetConfirmCreate2200 = RestAuthDetail;

export type AuthPasswordResetConfirmCreate2MutationRequest = PasswordResetConfirm;

export type AuthPasswordResetConfirmCreate2MutationResponse = AuthPasswordResetConfirmCreate2200;

export type AuthPasswordResetConfirmCreate2Mutation = {
    Response: AuthPasswordResetConfirmCreate2200;
    Request: AuthPasswordResetConfirmCreate2MutationRequest;
    PathParams: AuthPasswordResetConfirmCreate2PathParams;
    Errors: any;
};