/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { TokenVerify } from "./TokenVerify.ts";

export type AuthTokenVerifyCreate200 = Omit<NonNullable<TokenVerify>, "token">;

export type AuthTokenVerifyCreateMutationRequest = TokenVerify;

export type AuthTokenVerifyCreateMutationResponse = AuthTokenVerifyCreate200;

export type AuthTokenVerifyCreateMutation = {
    Response: AuthTokenVerifyCreate200;
    Request: AuthTokenVerifyCreateMutationRequest;
    Errors: any;
};