/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { UserDetails } from "./UserDetails.ts";

export type AuthUserRetrieve200 = UserDetails;

export type AuthUserRetrieveQueryResponse = AuthUserRetrieve200;

export type AuthUserRetrieveQuery = {
    Response: AuthUserRetrieve200;
    Errors: any;
};