/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PatchedUserDetails } from "./PatchedUserDetails.ts";
import type { UserDetails } from "./UserDetails.ts";

export type AuthUserPartialUpdate200 = UserDetails;

export type AuthUserPartialUpdateMutationRequest = Omit<NonNullable<PatchedUserDetails>, "pk" | "email" | "first_name" | "last_name">;

export type AuthUserPartialUpdateMutationResponse = AuthUserPartialUpdate200;

export type AuthUserPartialUpdateMutation = {
    Response: AuthUserPartialUpdate200;
    Request: AuthUserPartialUpdateMutationRequest;
    Errors: any;
};