/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RestAuthDetail } from "./RestAuthDetail.ts";

export type AuthLogoutCreate200 = RestAuthDetail;

export type AuthLogoutCreateMutationResponse = AuthLogoutCreate200;

export type AuthLogoutCreateMutation = {
    Response: AuthLogoutCreate200;
    Errors: any;
};