/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { TypeEnum } from "./TypeEnum.ts";
import type { UserMinDetails } from "./UserMinDetails.ts";
import type { UserRelationShort } from "./UserRelationShort.ts";

/**
 * @description Base serializer for all models.
*/
export type Conversation = {
    /**
     * @type integer
    */
    readonly id: number;
    readonly created_by_data: UserMinDetails | null;
    readonly updated_by_data: UserMinDetails | null;
    /**
     * @type array
    */
    readonly participants_data: UserRelationShort[];
    /**
     * @type string
    */
    readonly last_message: string;
    /**
     * @type string, date-time
    */
    readonly created_at: string;
    /**
     * @type string, date-time
    */
    readonly updated_at: string;
    /**
     * @maxLength 255
     * @type string | undefined
    */
    name?: string;
    /**
     * @description * `private` - Private\n* `group` - Group
     * @type string | undefined
    */
    type?: TypeEnum;
    /**
     * @type integer
    */
    created_by?: number | null;
    /**
     * @type integer
    */
    updated_by?: number | null;
    /**
     * @type array
    */
    participants: number[];
};