/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type ConversationsDestroyPathParams = {
    /**
     * @description A unique integer value identifying this conversation.
     * @type integer
    */
    id: number;
};

/**
 * @description No response body
*/
export type ConversationsDestroy204 = any;

export type ConversationsDestroyMutationResponse = ConversationsDestroy204;

export type ConversationsDestroyMutation = {
    Response: ConversationsDestroy204;
    PathParams: ConversationsDestroyPathParams;
    Errors: any;
};