/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Conversation } from "./Conversation.ts";

export type ConversationsCreate201 = Conversation;

export type ConversationsCreateMutationRequest = Omit<NonNullable<Conversation>, "id" | "participants_data" | "last_message" | "created_at" | "updated_at">;

export type ConversationsCreateMutationResponse = ConversationsCreate201;

export type ConversationsCreateMutation = {
    Response: ConversationsCreate201;
    Request: ConversationsCreateMutationRequest;
    Errors: any;
};