/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Message } from "./Message.ts";
import type { TypeEnum } from "./TypeEnum.ts";
import type { UserRelationShort } from "./UserRelationShort.ts";

export type Conversation = {
    /**
     * @type integer
    */
    readonly id: number;
    /**
     * @type array
    */
    readonly participants_data: UserRelationShort[];
    readonly last_message: Message;
    /**
     * @type string, date-time
    */
    readonly created_at: string;
    /**
     * @type string, date-time
    */
    readonly updated_at: string;
    /**
     * @maxLength 255
     * @type string | undefined
    */
    name?: string;
    /**
     * @description * `private` - Private\n* `group` - Group
     * @type string | undefined
    */
    type?: TypeEnum;
    /**
     * @type integer
    */
    created_by?: number | null;
    /**
     * @type integer
    */
    updated_by?: number | null;
    /**
     * @type array
    */
    participants: number[];
};