/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Conversation } from "./Conversation.ts";

export type ConversationsRetrievePathParams = {
    /**
     * @description A unique integer value identifying this conversation.
     * @type integer
    */
    id: number;
};

export type ConversationsRetrieve200 = Conversation;

export type ConversationsRetrieveQueryResponse = ConversationsRetrieve200;

export type ConversationsRetrieveQuery = {
    Response: ConversationsRetrieve200;
    PathParams: ConversationsRetrievePathParams;
    Errors: any;
};