/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Conversation } from "./Conversation.ts";
import type { PatchedConversation } from "./PatchedConversation.ts";

export type ConversationsPartialUpdatePathParams = {
    /**
     * @description A unique integer value identifying this conversation.
     * @type integer
    */
    id: number;
};

export type ConversationsPartialUpdate200 = Conversation;

export type ConversationsPartialUpdateMutationRequest = Omit<NonNullable<PatchedConversation>, "id" | "participants_data" | "last_message" | "created_at" | "updated_at">;

export type ConversationsPartialUpdateMutationResponse = ConversationsPartialUpdate200;

export type ConversationsPartialUpdateMutation = {
    Response: ConversationsPartialUpdate200;
    Request: ConversationsPartialUpdateMutationRequest;
    PathParams: ConversationsPartialUpdatePathParams;
    Errors: any;
};