/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PaginatedConversationList } from "./PaginatedConversationList.ts";

export const conversationsListQueryParamsTypeEnum = {
    "group": "group",
    "private": "private"
} as const;

export type ConversationsListQueryParamsTypeEnum = (typeof conversationsListQueryParamsTypeEnum)[keyof typeof conversationsListQueryParamsTypeEnum];

export type ConversationsListQueryParams = {
    /**
     * @description A page number within the paginated result set.
     * @type integer | undefined
    */
    page_no?: number;
    /**
     * @description Number of results to return per page.
     * @type integer | undefined
    */
    page_size?: number;
    /**
     * @type array | undefined
    */
    participants?: number[];
    /**
     * @description A search term.
     * @type string | undefined
    */
    search?: string;
    /**
     * @description * `private` - Private\n* `group` - Group
     * @type string | undefined
    */
    type?: ConversationsListQueryParamsTypeEnum;
};

export type ConversationsList200 = PaginatedConversationList;

export type ConversationsListQueryResponse = ConversationsList200;

export type ConversationsListQuery = {
    Response: ConversationsList200;
    QueryParams: ConversationsListQueryParams;
    Errors: any;
};