/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Conversation } from "./Conversation.ts";

export type ConversationsUpdatePathParams = {
    /**
     * @description A unique integer value identifying this conversation.
     * @type integer
    */
    id: number;
};

export type ConversationsUpdate200 = Conversation;

export type ConversationsUpdateMutationRequest = Omit<NonNullable<Conversation>, "id" | "created_by_data" | "updated_by_data" | "participants_data" | "last_message" | "created_at" | "updated_at">;

export type ConversationsUpdateMutationResponse = ConversationsUpdate200;

export type ConversationsUpdateMutation = {
    Response: ConversationsUpdate200;
    Request: ConversationsUpdateMutationRequest;
    PathParams: ConversationsUpdatePathParams;
    Errors: any;
};