/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PaginatedMessageList } from "./PaginatedMessageList.ts";

export type ConversationsMessagesListPathParams = {
    /**
     * @type string
    */
    parent_lookup_conversation: string;
};

export type ConversationsMessagesListQueryParams = {
    /**
     * @description Fetch results with IDs less than this value.
     * @type integer | undefined
    */
    before?: number;
    /**
     * @description Number of results to return. Default is 30.
     * @type integer | undefined
    */
    limit?: number;
};

export type ConversationsMessagesList200 = PaginatedMessageList;

export type ConversationsMessagesListQueryResponse = ConversationsMessagesList200;

export type ConversationsMessagesListQuery = {
    Response: ConversationsMessagesList200;
    PathParams: ConversationsMessagesListPathParams;
    QueryParams: ConversationsMessagesListQueryParams;
    Errors: any;
};