/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type CurrentUserDetail = {
    /**
     * @type integer
    */
    readonly id: number;
    /**
     * @maxLength 255
     * @type string | undefined
    */
    name?: string;
    /**
     * @maxLength 254
     * @type string, email
    */
    email: string;
};