/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type GeneratePresignedURLRequest = {
    /**
     * @type string
    */
    filename: string;
    /**
     * @type string
    */
    content_type: string;
};