/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { UserDetails } from "./UserDetails.ts";

/**
 * @description Serializer for JWT authentication.
*/
export type JWT = {
    /**
     * @type string
    */
    access: string;
    /**
     * @type string
    */
    refresh: string;
    /**
     * @description User model w/o password
     * @type object
    */
    user: UserDetails;
};