/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type Login = {
    /**
     * @type string | undefined
    */
    username?: string;
    /**
     * @type string | undefined, email
    */
    email?: string;
    /**
     * @type string
    */
    password: string;
};