/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Message } from "./Message.ts";

export type MessagesCreate201 = Omit<NonNullable<Message>, "attachments">;

export type MessagesCreateMutationRequest = Omit<NonNullable<Message>, "id" | "sender_data" | "attachments_data" | "reply_quote" | "created_at" | "updated_at">;

export type MessagesCreateMutationResponse = MessagesCreate201;

export type MessagesCreateMutation = {
    Response: MessagesCreate201;
    Request: MessagesCreateMutationRequest;
    Errors: any;
};