/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Message } from "./Message.ts";

export type MessagesRetrievePathParams = {
    /**
     * @description A unique integer value identifying this message.
     * @type integer
    */
    id: number;
};

export type MessagesRetrieve200 = Message;

export type MessagesRetrieveQueryResponse = MessagesRetrieve200;

export type MessagesRetrieveQuery = {
    Response: MessagesRetrieve200;
    PathParams: MessagesRetrievePathParams;
    Errors: any;
};