/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { MessageAttachment } from "./MessageAttachment.ts";
import type { MessageAttachmentRequest } from "./MessageAttachmentRequest.ts";
import type { UserMinDetails } from "./UserMinDetails.ts";
import type { UserRelationShort } from "./UserRelationShort.ts";

/**
 * @description Base serializer for all models.
*/
export type Message = {
    /**
     * @type integer
    */
    readonly id: number;
    readonly created_by_data: UserMinDetails | null;
    readonly updated_by_data: UserMinDetails | null;
    readonly sender_data: UserRelationShort;
    /**
     * @type array
    */
    attachments: MessageAttachmentRequest[];
    /**
     * @type array
    */
    readonly attachments_data: MessageAttachment[];
    /**
     * @type string, date-time
    */
    readonly created_at: string;
    /**
     * @type string, date-time
    */
    readonly updated_at: string;
    /**
     * @type string
    */
    content: string;
    /**
     * @type boolean | undefined
    */
    is_read?: boolean;
    /**
     * @type integer
    */
    created_by?: number | null;
    /**
     * @type integer
    */
    updated_by?: number | null;
    /**
     * @type integer
    */
    conversation: number;
    /**
     * @type integer
    */
    sender: number;
};