/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export const messageTypeEnumEnum = {
    "text": "text",
    "audio": "audio",
    "file": "file"
} as const;

export type MessageTypeEnumEnum = (typeof messageTypeEnumEnum)[keyof typeof messageTypeEnumEnum];

/**
 * @description * `text` - Text\n* `audio` - Audio\n* `file` - File
*/
export type MessageTypeEnum = MessageTypeEnumEnum;