/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Message } from "./Message.ts";

export type MessagesUpdatePathParams = {
    /**
     * @description A unique integer value identifying this message.
     * @type integer
    */
    id: number;
};

export type MessagesUpdate200 = Omit<NonNullable<Message>, "attachments">;

export type MessagesUpdateMutationRequest = Omit<NonNullable<Message>, "id" | "sender_data" | "attachments_data" | "reply_quote" | "created_at" | "updated_at">;

export type MessagesUpdateMutationResponse = MessagesUpdate200;

export type MessagesUpdateMutation = {
    Response: MessagesUpdate200;
    Request: MessagesUpdateMutationRequest;
    PathParams: MessagesUpdatePathParams;
    Errors: any;
};