/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Message } from "./Message.ts";

export type MessagesUpdatePathParams = {
    /**
     * @description A unique integer value identifying this message.
     * @type integer
    */
    id: number;
};

export type MessagesUpdate200 = Message;

export type MessagesUpdateMutationRequest = Omit<NonNullable<Message>, "id" | "created_by_data" | "updated_by_data" | "sender_data" | "created_at" | "updated_at">;

export type MessagesUpdateMutationResponse = MessagesUpdate200;

export type MessagesUpdateMutation = {
    Response: MessagesUpdate200;
    Request: MessagesUpdateMutationRequest;
    PathParams: MessagesUpdatePathParams;
    Errors: any;
};