/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Message } from "./Message.ts";
import type { PatchedMessage } from "./PatchedMessage.ts";

export type MessagesPartialUpdatePathParams = {
    /**
     * @description A unique integer value identifying this message.
     * @type integer
    */
    id: number;
};

export type MessagesPartialUpdate200 = Omit<NonNullable<Message>, "attachments">;

export type MessagesPartialUpdateMutationRequest = Omit<NonNullable<PatchedMessage>, "id" | "sender_data" | "attachments_data" | "reply_quote" | "created_at" | "updated_at">;

export type MessagesPartialUpdateMutationResponse = MessagesPartialUpdate200;

export type MessagesPartialUpdateMutation = {
    Response: MessagesPartialUpdate200;
    Request: MessagesPartialUpdateMutationRequest;
    PathParams: MessagesPartialUpdatePathParams;
    Errors: any;
};