/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type MessageAttachment = {
    /**
     * @type integer
    */
    readonly id: number;
    /**
     * @maxLength 200
     * @type string, uri
    */
    file_url: string;
    /**
     * @maxLength 512
     * @type string
    */
    key: string;
    /**
     * @type integer
    */
    message: number;
};