/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { MessageAttachment } from "./MessageAttachment.ts";
import type { MessageAttachmentRequest } from "./MessageAttachmentRequest.ts";
import type { MessageTypeEnum } from "./MessageTypeEnum.ts";
import type { ReplyQuote } from "./ReplyQuote.ts";
import type { UserRelationShort } from "./UserRelationShort.ts";

export type Message = {
    /**
     * @type integer
    */
    readonly id: number;
    readonly sender_data: UserRelationShort;
    /**
     * @type array
    */
    attachments: MessageAttachmentRequest[];
    /**
     * @type array
    */
    readonly attachments_data: MessageAttachment[];
    readonly reply_quote: ReplyQuote;
    /**
     * @type string, date-time
    */
    readonly created_at: string;
    /**
     * @type string, date-time
    */
    readonly updated_at: string;
    /**
     * @type string
    */
    content: string;
    reply_to?: any;
    /**
     * @description * `text` - Text\n* `audio` - Audio\n* `file` - File
     * @type string | undefined
    */
    message_type?: MessageTypeEnum;
    /**
     * @type boolean | undefined
    */
    is_read?: boolean;
    /**
     * @type boolean | undefined
    */
    is_edited?: boolean;
    /**
     * @type boolean | undefined
    */
    is_starred?: boolean;
    reactions?: any;
    /**
     * @type integer
    */
    created_by?: number | null;
    /**
     * @type integer
    */
    updated_by?: number | null;
    /**
     * @type integer
    */
    conversation: number;
    /**
     * @type integer
    */
    sender?: number | null;
    /**
     * @type array | undefined
    */
    mentioned_users?: number[];
};