/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type MessageAttachmentRequest = {
    /**
     * @type string
    */
    file_url: string;
    /**
     * @type string
    */
    key: string;
};