/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type MessagesDestroyPathParams = {
    /**
     * @description A unique integer value identifying this message.
     * @type integer
    */
    id: number;
};

/**
 * @description No response body
*/
export type MessagesDestroy204 = any;

export type MessagesDestroyMutationResponse = MessagesDestroy204;

export type MessagesDestroyMutation = {
    Response: MessagesDestroy204;
    PathParams: MessagesDestroyPathParams;
    Errors: any;
};