/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PaginatedMessageList } from "./PaginatedMessageList.ts";

export type MessagesListQueryParams = {
    /**
     * @type integer | undefined
    */
    conversation?: number;
    /**
     * @type array | undefined
    */
    conversation__participants?: number[];
    /**
     * @description A page number within the paginated result set.
     * @type integer | undefined
    */
    page_no?: number;
    /**
     * @description Number of results to return per page.
     * @type integer | undefined
    */
    page_size?: number;
    /**
     * @description A search term.
     * @type string | undefined
    */
    search?: string;
    /**
     * @type integer | undefined
    */
    sender?: number;
};

export type MessagesList200 = PaginatedMessageList;

export type MessagesListQueryResponse = MessagesList200;

export type MessagesListQuery = {
    Response: MessagesList200;
    QueryParams: MessagesListQueryParams;
    Errors: any;
};