/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { User } from "./User.ts";

export type PaginatedUserList = {
    /**
     * @type integer
    */
    count: number;
    /**
     * @type string, uri
    */
    next?: string | null;
    /**
     * @type string, uri
    */
    previous?: string | null;
    /**
     * @type array
    */
    results: User[];
};