/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Task } from "./Task.ts";

export type PaginatedTaskList = {
    /**
     * @type integer
    */
    count: number;
    /**
     * @type string, uri
    */
    next?: string | null;
    /**
     * @type string, uri
    */
    previous?: string | null;
    /**
     * @type array
    */
    results: Task[];
};