/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Conversation } from "./Conversation.ts";

export type PaginatedConversationList = {
    /**
     * @type integer
    */
    count: number;
    /**
     * @type string, uri
    */
    next?: string | null;
    /**
     * @type string, uri
    */
    previous?: string | null;
    /**
     * @type array
    */
    results: Conversation[];
};