/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Project } from "./Project.ts";

export type PaginatedProjectList = {
    /**
     * @type integer
    */
    count: number;
    /**
     * @type string, uri
    */
    next?: string | null;
    /**
     * @type string, uri
    */
    previous?: string | null;
    /**
     * @type array
    */
    results: Project[];
};