/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { UserProject } from "./UserProject.ts";

export type PaginatedUserProjectList = {
    /**
     * @type integer
    */
    count: number;
    /**
     * @type string, uri
    */
    next?: string | null;
    /**
     * @type string, uri
    */
    previous?: string | null;
    /**
     * @type array
    */
    results: UserProject[];
};