/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ProjectWiseMember } from "./ProjectWiseMember.ts";

export type PaginatedProjectWiseMemberList = {
    /**
     * @type integer
    */
    count: number;
    /**
     * @type string, uri
    */
    next?: string | null;
    /**
     * @type string, uri
    */
    previous?: string | null;
    /**
     * @type array
    */
    results: ProjectWiseMember[];
};