/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Message } from "./Message.ts";

export type PaginatedMessageList = {
    /**
     * @type integer
    */
    count: number;
    /**
     * @type integer
    */
    next_before?: number | null;
    /**
     * @type array
    */
    results: Message[];
};