/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


/**
 * @description Base serializer for all models.
*/
export type PatchedTaskStatus = {
    /**
     * @type integer | undefined
    */
    readonly id?: number;
    /**
     * @maxLength 128
     * @type string | undefined
    */
    title?: string;
    /**
     * @type integer
    */
    parent_status?: number | null;
};