/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { MessageAttachment } from "./MessageAttachment.ts";
import type { MessageAttachmentRequest } from "./MessageAttachmentRequest.ts";
import type { UserMinDetails } from "./UserMinDetails.ts";
import type { UserRelationShort } from "./UserRelationShort.ts";

/**
 * @description Base serializer for all models.
*/
export type PatchedMessage = {
    /**
     * @type integer | undefined
    */
    readonly id?: number;
    readonly created_by_data?: UserMinDetails | null;
    readonly updated_by_data?: UserMinDetails | null;
    readonly sender_data?: UserRelationShort;
    /**
     * @type array | undefined
    */
    attachments?: MessageAttachmentRequest[];
    /**
     * @type array | undefined
    */
    readonly attachments_data?: MessageAttachment[];
    /**
     * @type string | undefined, date-time
    */
    readonly created_at?: string;
    /**
     * @type string | undefined, date-time
    */
    readonly updated_at?: string;
    /**
     * @type string | undefined
    */
    content?: string;
    /**
     * @type boolean | undefined
    */
    is_read?: boolean;
    /**
     * @type integer
    */
    created_by?: number | null;
    /**
     * @type integer
    */
    updated_by?: number | null;
    /**
     * @type integer | undefined
    */
    conversation?: number;
    /**
     * @type integer | undefined
    */
    sender?: number;
};