/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type PatchedUser = {
    /**
     * @maxLength 255
     * @type string | undefined
    */
    name?: string;
    /**
     * @maxLength 254
     * @type string | undefined, email
    */
    email?: string;
    /**
     * @type integer | undefined
    */
    readonly id?: number;
};