/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { UserMinDetails } from "./UserMinDetails.ts";
import type { UserRelationShort } from "./UserRelationShort.ts";

/**
 * @description Base serializer for all models.
*/
export type PatchedProject = {
    /**
     * @type integer | undefined
    */
    readonly id?: number;
    readonly created_by_data?: UserMinDetails | null;
    readonly updated_by_data?: UserMinDetails | null;
    readonly owner_data?: UserRelationShort;
    /**
     * @type string | undefined, date-time
    */
    readonly created_at?: string;
    /**
     * @type string | undefined, date-time
    */
    readonly updated_at?: string;
    /**
     * @maxLength 256
     * @type string | undefined
    */
    title?: string;
    /**
     * @type string | undefined
    */
    description?: string;
    /**
     * @type integer
    */
    created_by?: number | null;
    /**
     * @type integer
    */
    updated_by?: number | null;
    /**
     * @type integer
    */
    owner?: number | null;
};