/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


/**
 * @description User model w/o password
*/
export type PatchedUserDetails = {
    /**
     * @type integer | undefined
    */
    readonly pk?: number;
    /**
     * @type string | undefined, email
    */
    readonly email?: string;
    /**
     * @type string | undefined
    */
    readonly first_name?: string;
    /**
     * @type string | undefined
    */
    readonly last_name?: string;
};