/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ProjectRelationShort } from "./ProjectRelationShort.ts";
import type { Task } from "./Task.ts";
import type { TaskStatus } from "./TaskStatus.ts";
import type { UserMinDetails } from "./UserMinDetails.ts";
import type { UserRelationShort } from "./UserRelationShort.ts";

/**
 * @description Base serializer for all models.
*/
export type PatchedTaskDetail = {
    /**
     * @type integer | undefined
    */
    readonly id?: number;
    readonly created_by_data?: UserMinDetails | null;
    readonly updated_by_data?: UserMinDetails | null;
    readonly project_data?: ProjectRelationShort;
    readonly assignee_data?: UserRelationShort;
    readonly status_data?: TaskStatus;
    /**
     * @type array | undefined
    */
    readonly subtasks_data?: Task[];
    /**
     * @type string | undefined, date-time
    */
    readonly created_at?: string;
    /**
     * @type string | undefined, date-time
    */
    readonly updated_at?: string;
    /**
     * @type string | undefined
    */
    title?: string;
    /**
     * @type string | undefined
    */
    description?: string;
    /**
     * @minLength 0
     * @maxLength 2147483647
     * @type integer | undefined
    */
    level?: number;
    /**
     * @type boolean | undefined
    */
    is_done?: boolean;
    /**
     * @type integer
    */
    created_by?: number | null;
    /**
     * @type integer
    */
    updated_by?: number | null;
    /**
     * @type integer | undefined
    */
    project?: number;
    /**
     * @type integer
    */
    parent_task?: number | null;
    /**
     * @type integer
    */
    status?: number | null;
    /**
     * @type integer
    */
    assignee?: number | null;
};