/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type PatchedUser = {
    /**
     * @maxLength 255
     * @type string | undefined
    */
    name?: string;
    /**
     * @type string | undefined, uri
    */
    readonly url?: string;
    /**
     * @maxLength 254
     * @type string | undefined, email
    */
    email?: string;
};