/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ProjectRelationShort } from "./ProjectRelationShort.ts";
import type { UserMinDetails } from "./UserMinDetails.ts";
import type { UserRelationShort } from "./UserRelationShort.ts";

/**
 * @description Base serializer for all models.
*/
export type PatchedProjectMember = {
    /**
     * @type integer | undefined
    */
    readonly id?: number;
    readonly created_by_data?: UserMinDetails | null;
    readonly updated_by_data?: UserMinDetails | null;
    readonly project_data?: ProjectRelationShort;
    readonly member_data?: UserRelationShort;
    /**
     * @type string | undefined, date-time
    */
    readonly created_at?: string;
    /**
     * @type string | undefined, date-time
    */
    readonly updated_at?: string;
    /**
     * @type integer
    */
    created_by?: number | null;
    /**
     * @type integer
    */
    updated_by?: number | null;
    /**
     * @type integer | undefined
    */
    project?: number;
    /**
     * @type integer | undefined
    */
    member?: number;
};