/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ProjectMember } from "./ProjectMember.ts";

export type ProjectMembersRetrievePathParams = {
    /**
     * @description A unique integer value identifying this project member.
     * @type integer
    */
    id: number;
};

export type ProjectMembersRetrieve200 = ProjectMember;

export type ProjectMembersRetrieveQueryResponse = ProjectMembersRetrieve200;

export type ProjectMembersRetrieveQuery = {
    Response: ProjectMembersRetrieve200;
    PathParams: ProjectMembersRetrievePathParams;
    Errors: any;
};