/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type ProjectMembersDestroyPathParams = {
    /**
     * @description A unique integer value identifying this project member.
     * @type integer
    */
    id: number;
};

/**
 * @description No response body
*/
export type ProjectMembersDestroy204 = any;

export type ProjectMembersDestroyMutationResponse = ProjectMembersDestroy204;

export type ProjectMembersDestroyMutation = {
    Response: ProjectMembersDestroy204;
    PathParams: ProjectMembersDestroyPathParams;
    Errors: any;
};