/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ProjectRelationShort } from "./ProjectRelationShort.ts";

export type ProjectSearchResults = {
    /**
     * @type array
    */
    results: ProjectRelationShort[];
};