/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ProjectRelationShort } from "./ProjectRelationShort.ts";
import type { UserMinDetails } from "./UserMinDetails.ts";
import type { UserRelationShort } from "./UserRelationShort.ts";

/**
 * @description Base serializer for all models.
*/
export type ProjectMember = {
    /**
     * @type integer
    */
    readonly id: number;
    readonly created_by_data: UserMinDetails | null;
    readonly updated_by_data: UserMinDetails | null;
    readonly project_data: ProjectRelationShort;
    readonly member_data: UserRelationShort;
    /**
     * @type string, date-time
    */
    readonly created_at: string;
    /**
     * @type string, date-time
    */
    readonly updated_at: string;
    /**
     * @type integer
    */
    created_by?: number | null;
    /**
     * @type integer
    */
    updated_by?: number | null;
    /**
     * @type integer
    */
    project: number;
    /**
     * @type integer
    */
    member: number;
};