/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PaginatedProjectList } from "./PaginatedProjectList.ts";

export type ProjectsListQueryParams = {
    /**
     * @description A page number within the paginated result set.
     * @type integer | undefined
    */
    page_no?: number;
    /**
     * @description Number of results to return per page.
     * @type integer | undefined
    */
    page_size?: number;
};

export type ProjectsList200 = PaginatedProjectList;

export type ProjectsListQueryResponse = ProjectsList200;

export type ProjectsListQuery = {
    Response: ProjectsList200;
    QueryParams: ProjectsListQueryParams;
    Errors: any;
};