/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type ProjectsDestroyPathParams = {
    /**
     * @description A unique integer value identifying this project.
     * @type integer
    */
    id: number;
};

/**
 * @description No response body
*/
export type ProjectsDestroy204 = any;

export type ProjectsDestroyMutationResponse = ProjectsDestroy204;

export type ProjectsDestroyMutation = {
    Response: ProjectsDestroy204;
    PathParams: ProjectsDestroyPathParams;
    Errors: any;
};