/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ProjectSearchResults } from "./ProjectSearchResults.ts";

export type ProjectsSearchRetrieve200 = ProjectSearchResults;

export type ProjectsSearchRetrieveQueryResponse = ProjectsSearchRetrieve200;

export type ProjectsSearchRetrieveQuery = {
    Response: ProjectsSearchRetrieve200;
    Errors: any;
};