/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PatchedProjectMember } from "./PatchedProjectMember.ts";
import type { ProjectMember } from "./ProjectMember.ts";

export type ProjectMembersPartialUpdatePathParams = {
    /**
     * @description A unique integer value identifying this project member.
     * @type integer
    */
    id: number;
};

export type ProjectMembersPartialUpdate200 = ProjectMember;

export type ProjectMembersPartialUpdateMutationRequest = Omit<NonNullable<PatchedProjectMember>, "id" | "created_by_data" | "updated_by_data" | "project_data" | "member_data" | "created_at" | "updated_at">;

export type ProjectMembersPartialUpdateMutationResponse = ProjectMembersPartialUpdate200;

export type ProjectMembersPartialUpdateMutation = {
    Response: ProjectMembersPartialUpdate200;
    Request: ProjectMembersPartialUpdateMutationRequest;
    PathParams: ProjectMembersPartialUpdatePathParams;
    Errors: any;
};