/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PaginatedProjectWiseMemberList } from "./PaginatedProjectWiseMemberList.ts";

export type ProjectsProjectWiseProjectMembersListPathParams = {
    /**
     * @type string
    */
    parent_lookup_project: string;
};

export type ProjectsProjectWiseProjectMembersListQueryParams = {
    /**
     * @type string | undefined
    */
    member__email__icontains?: string;
    /**
     * @type integer | undefined
    */
    member__id?: number;
    /**
     * @type string | undefined
    */
    member__name__icontains?: string;
    /**
     * @description A page number within the paginated result set.
     * @type integer | undefined
    */
    page_no?: number;
    /**
     * @description Number of results to return per page.
     * @type integer | undefined
    */
    page_size?: number;
    /**
     * @description A search term.
     * @type string | undefined
    */
    search?: string;
};

export type ProjectsProjectWiseProjectMembersList200 = PaginatedProjectWiseMemberList;

export type ProjectsProjectWiseProjectMembersListQueryResponse = ProjectsProjectWiseProjectMembersList200;

export type ProjectsProjectWiseProjectMembersListQuery = {
    Response: ProjectsProjectWiseProjectMembersList200;
    PathParams: ProjectsProjectWiseProjectMembersListPathParams;
    QueryParams: ProjectsProjectWiseProjectMembersListQueryParams;
    Errors: any;
};