/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ProjectMember } from "./ProjectMember.ts";

export type ProjectMembersUpdatePathParams = {
    /**
     * @description A unique integer value identifying this project member.
     * @type integer
    */
    id: number;
};

export type ProjectMembersUpdate200 = ProjectMember;

export type ProjectMembersUpdateMutationRequest = Omit<NonNullable<ProjectMember>, "id" | "created_by_data" | "updated_by_data" | "project_data" | "member_data" | "created_at" | "updated_at">;

export type ProjectMembersUpdateMutationResponse = ProjectMembersUpdate200;

export type ProjectMembersUpdateMutation = {
    Response: ProjectMembersUpdate200;
    Request: ProjectMembersUpdateMutationRequest;
    PathParams: ProjectMembersUpdatePathParams;
    Errors: any;
};