/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PaginatedTaskList } from "./PaginatedTaskList.ts";

export type ProjectsTasksListPathParams = {
    /**
     * @type string
    */
    parent_lookup_project: string;
};

export type ProjectsTasksListQueryParams = {
    /**
     * @type string | undefined, date-time
    */
    created_at?: string;
    /**
     * @type string | undefined, date-time
    */
    created_at__gte?: string;
    /**
     * @type string | undefined, date-time
    */
    created_at__lte?: string;
    /**
     * @type integer | undefined
    */
    created_by?: number;
    /**
     * @type string | undefined
    */
    description__icontains?: string;
    /**
     * @type boolean | undefined
    */
    is_done?: boolean;
    /**
     * @type integer | undefined
    */
    level?: number;
    /**
     * @description A page number within the paginated result set.
     * @type integer | undefined
    */
    page_no?: number;
    /**
     * @description Number of results to return per page.
     * @type integer | undefined
    */
    page_size?: number;
    /**
     * @type integer | undefined
    */
    parent_task?: number;
    /**
     * @description A search term.
     * @type string | undefined
    */
    search?: string;
    /**
     * @type integer | undefined
    */
    status?: number;
    /**
     * @type string | undefined
    */
    title__icontains?: string;
    /**
     * @type string | undefined, date-time
    */
    updated_at?: string;
    /**
     * @type string | undefined, date-time
    */
    updated_at__gte?: string;
    /**
     * @type string | undefined, date-time
    */
    updated_at__lte?: string;
    /**
     * @type integer | undefined
    */
    updated_by?: number;
};

export type ProjectsTasksList200 = PaginatedTaskList;

export type ProjectsTasksListQueryResponse = ProjectsTasksList200;

export type ProjectsTasksListQuery = {
    Response: ProjectsTasksList200;
    PathParams: ProjectsTasksListPathParams;
    QueryParams: ProjectsTasksListQueryParams;
    Errors: any;
};