/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PatchedProject } from "./PatchedProject.ts";
import type { Project } from "./Project.ts";

export type ProjectsPartialUpdatePathParams = {
    /**
     * @description A unique integer value identifying this project.
     * @type integer
    */
    id: number;
};

export type ProjectsPartialUpdate200 = Project;

export type ProjectsPartialUpdateMutationRequest = Omit<NonNullable<PatchedProject>, "id" | "created_by_data" | "updated_by_data" | "owner_data" | "created_at" | "updated_at">;

export type ProjectsPartialUpdateMutationResponse = ProjectsPartialUpdate200;

export type ProjectsPartialUpdateMutation = {
    Response: ProjectsPartialUpdate200;
    Request: ProjectsPartialUpdateMutationRequest;
    PathParams: ProjectsPartialUpdatePathParams;
    Errors: any;
};