/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { UserRelationShort } from "./UserRelationShort.ts";

/**
 * @description Base serializer for all models.
*/
export type ProjectRelationShort = {
    /**
     * @type integer
    */
    readonly id: number;
    /**
     * @maxLength 256
     * @type string
    */
    title: string;
    readonly owner_data: UserRelationShort;
};