/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Project } from "./Project.ts";

export type ProjectsCreate201 = Project;

export type ProjectsCreateMutationRequest = Omit<NonNullable<Project>, "id" | "created_by_data" | "updated_by_data" | "created_at" | "updated_at">;

export type ProjectsCreateMutationResponse = ProjectsCreate201;

export type ProjectsCreateMutation = {
    Response: ProjectsCreate201;
    Request: ProjectsCreateMutationRequest;
    Errors: any;
};