/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { TaskSearchResults } from "./TaskSearchResults.ts";

export type ProjectsTasksSearchRetrievePathParams = {
    /**
     * @type string
    */
    parent_lookup_project: string;
};

export type ProjectsTasksSearchRetrieve200 = TaskSearchResults;

export type ProjectsTasksSearchRetrieveQueryResponse = ProjectsTasksSearchRetrieve200;

export type ProjectsTasksSearchRetrieveQuery = {
    Response: ProjectsTasksSearchRetrieve200;
    PathParams: ProjectsTasksSearchRetrievePathParams;
    Errors: any;
};