/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { UserRelationShort } from "./UserRelationShort.ts";

/**
 * @description Base serializer for all models.
*/
export type ProjectWiseMember = {
    readonly member_data: UserRelationShort | null;
    /**
     * @type string, date-time
    */
    readonly created_at: string;
};