/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Project } from "./Project.ts";

export type ProjectsUpdatePathParams = {
    /**
     * @description A unique integer value identifying this project.
     * @type integer
    */
    id: number;
};

export type ProjectsUpdate200 = Project;

export type ProjectsUpdateMutationRequest = Omit<NonNullable<Project>, "id" | "created_by_data" | "updated_by_data" | "created_at" | "updated_at">;

export type ProjectsUpdateMutationResponse = ProjectsUpdate200;

export type ProjectsUpdateMutation = {
    Response: ProjectsUpdate200;
    Request: ProjectsUpdateMutationRequest;
    PathParams: ProjectsUpdatePathParams;
    Errors: any;
};