/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ProjectMember } from "./ProjectMember.ts";

export type ProjectMembersCreate201 = ProjectMember;

export type ProjectMembersCreateMutationRequest = Omit<NonNullable<ProjectMember>, "id" | "created_by_data" | "updated_by_data" | "project_data" | "member_data" | "created_at" | "updated_at">;

export type ProjectMembersCreateMutationResponse = ProjectMembersCreate201;

export type ProjectMembersCreateMutation = {
    Response: ProjectMembersCreate201;
    Request: ProjectMembersCreateMutationRequest;
    Errors: any;
};