/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Project } from "./Project.ts";

export type ProjectsRetrievePathParams = {
    /**
     * @description A unique integer value identifying this project.
     * @type integer
    */
    id: number;
};

export type ProjectsRetrieve200 = Project;

export type ProjectsRetrieveQueryResponse = ProjectsRetrieve200;

export type ProjectsRetrieveQuery = {
    Response: ProjectsRetrieve200;
    PathParams: ProjectsRetrievePathParams;
    Errors: any;
};