/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type ReplyQuote = {
    /**
     * @type string
    */
    message_id: string;
    /**
     * @type string
    */
    content: string;
};