/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GeneratePresignedURLRequest } from "./GeneratePresignedURLRequest.ts";
import type { GeneratePresignedURLResponse } from "./GeneratePresignedURLResponse.ts";
import type { Response } from "./Response.ts";

export type S3PresignedUrlCreate200 = GeneratePresignedURLResponse;

export type S3PresignedUrlCreate400 = Response;

export type S3PresignedUrlCreateMutationRequest = GeneratePresignedURLRequest;

export type S3PresignedUrlCreateMutationResponse = S3PresignedUrlCreate200;

export type S3PresignedUrlCreateMutation = {
    Response: S3PresignedUrlCreate200;
    Request: S3PresignedUrlCreateMutationRequest;
    Errors: S3PresignedUrlCreate400;
};