/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { StateTransition } from "./StateTransition.ts";

export type StateTransitionsMap = {
    /**
     * @type object
    */
    state_transitions_map: {
        [key: string]: StateTransition;
    };
};