/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


/**
 * @description Base serializer for all models.
*/
export type StateTransition = {
    /**
     * @type integer
    */
    readonly id: number;
    /**
     * @maxLength 128
     * @type string
    */
    title: string;
    /**
     * @type array
    */
    children: number[];
};