/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PatchedTaskDetail } from "./PatchedTaskDetail.ts";
import type { TaskDetail } from "./TaskDetail.ts";

export type TasksPartialUpdatePathParams = {
    /**
     * @description A unique integer value identifying this task.
     * @type integer
    */
    id: number;
};

export type TasksPartialUpdate200 = TaskDetail;

export type TasksPartialUpdateMutationRequest = Omit<NonNullable<PatchedTaskDetail>, "id" | "created_by_data" | "updated_by_data" | "project_data" | "assignee_data" | "status_data" | "subtasks_data" | "created_at" | "updated_at">;

export type TasksPartialUpdateMutationResponse = TasksPartialUpdate200;

export type TasksPartialUpdateMutation = {
    Response: TasksPartialUpdate200;
    Request: TasksPartialUpdateMutationRequest;
    PathParams: TasksPartialUpdatePathParams;
    Errors: any;
};