/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { TaskDetail } from "./TaskDetail.ts";

export type TasksCreate201 = TaskDetail;

export type TasksCreateMutationRequest = Omit<NonNullable<TaskDetail>, "id" | "created_by_data" | "updated_by_data" | "project_data" | "assignee_data" | "status_data" | "subtasks_data" | "created_at" | "updated_at">;

export type TasksCreateMutationResponse = TasksCreate201;

export type TasksCreateMutation = {
    Response: TasksCreate201;
    Request: TasksCreateMutationRequest;
    Errors: any;
};