/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ProjectRelationShort } from "./ProjectRelationShort.ts";
import type { TaskStatus } from "./TaskStatus.ts";
import type { UserMinDetails } from "./UserMinDetails.ts";
import type { UserRelationShort } from "./UserRelationShort.ts";

/**
 * @description Base serializer for all models.
*/
export type Task = {
    /**
     * @type integer
    */
    readonly id: number;
    readonly created_by_data: UserMinDetails | null;
    readonly updated_by_data: UserMinDetails | null;
    readonly project_data: ProjectRelationShort;
    readonly assignee_data: UserRelationShort;
    /**
     * @default 0
     * @type integer
    */
    readonly subtasks_count: number;
    readonly status_data: TaskStatus;
    /**
     * @type string, date-time
    */
    readonly created_at: string;
    /**
     * @type string, date-time
    */
    readonly updated_at: string;
    /**
     * @type string
    */
    title: string;
    /**
     * @type string | undefined
    */
    description?: string;
    /**
     * @minLength 0
     * @maxLength 2147483647
     * @type integer | undefined
    */
    level?: number;
    /**
     * @type boolean | undefined
    */
    is_done?: boolean;
    /**
     * @type integer
    */
    created_by?: number | null;
    /**
     * @type integer
    */
    updated_by?: number | null;
    /**
     * @type integer
    */
    project: number;
    /**
     * @type integer
    */
    parent_task?: number | null;
    /**
     * @type integer
    */
    status?: number | null;
    /**
     * @type integer
    */
    assignee?: number | null;
};