/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { TaskStatus } from "./TaskStatus.ts";

/**
 * @description Base serializer for all models.
*/
export type TaskDetailsShort = {
    /**
     * @type integer
    */
    readonly id: number;
    /**
     * @type string
    */
    title: string;
    readonly status_data: TaskStatus;
};