/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Task } from "./Task.ts";

export type TasksCreate201 = Task;

export type TasksCreateMutationRequest = Omit<NonNullable<Task>, "id" | "created_by_data" | "updated_by_data" | "project_data" | "assignee_data" | "subtasks_count" | "created_at" | "updated_at">;

export type TasksCreateMutationResponse = TasksCreate201;

export type TasksCreateMutation = {
    Response: TasksCreate201;
    Request: TasksCreateMutationRequest;
    Errors: any;
};