/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PatchedTaskStatus } from "./PatchedTaskStatus.ts";
import type { TaskStatus } from "./TaskStatus.ts";

export type TaskStatusPartialUpdatePathParams = {
    /**
     * @description A unique integer value identifying this task status.
     * @type integer
    */
    id: number;
};

export type TaskStatusPartialUpdate200 = TaskStatus;

export type TaskStatusPartialUpdateMutationRequest = Omit<NonNullable<PatchedTaskStatus>, "id">;

export type TaskStatusPartialUpdateMutationResponse = TaskStatusPartialUpdate200;

export type TaskStatusPartialUpdateMutation = {
    Response: TaskStatusPartialUpdate200;
    Request: TaskStatusPartialUpdateMutationRequest;
    PathParams: TaskStatusPartialUpdatePathParams;
    Errors: any;
};