/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { TaskStatus } from "./TaskStatus.ts";

export type TaskStatusList200 = TaskStatus[];

export type TaskStatusListQueryResponse = TaskStatusList200;

export type TaskStatusListQuery = {
    Response: TaskStatusList200;
    Errors: any;
};