/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { TaskStatus } from "./TaskStatus.ts";

export type TaskStatusRetrievePathParams = {
    /**
     * @description A unique integer value identifying this task status.
     * @type integer
    */
    id: number;
};

export type TaskStatusRetrieve200 = TaskStatus;

export type TaskStatusRetrieveQueryResponse = TaskStatusRetrieve200;

export type TaskStatusRetrieveQuery = {
    Response: TaskStatusRetrieve200;
    PathParams: TaskStatusRetrievePathParams;
    Errors: any;
};