/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { TaskStatus } from "./TaskStatus.ts";

export type TaskStatusUpdatePathParams = {
    /**
     * @description A unique integer value identifying this task status.
     * @type integer
    */
    id: number;
};

export type TaskStatusUpdate200 = TaskStatus;

export type TaskStatusUpdateMutationRequest = Omit<NonNullable<TaskStatus>, "id">;

export type TaskStatusUpdateMutationResponse = TaskStatusUpdate200;

export type TaskStatusUpdateMutation = {
    Response: TaskStatusUpdate200;
    Request: TaskStatusUpdateMutationRequest;
    PathParams: TaskStatusUpdatePathParams;
    Errors: any;
};