/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { StateTransitionsMap } from "./StateTransitionsMap.ts";

export type TaskStatusTaskStatusWorkflowRetrieve200 = StateTransitionsMap;

export type TaskStatusTaskStatusWorkflowRetrieveQueryResponse = TaskStatusTaskStatusWorkflowRetrieve200;

export type TaskStatusTaskStatusWorkflowRetrieveQuery = {
    Response: TaskStatusTaskStatusWorkflowRetrieve200;
    Errors: any;
};