/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { TaskDetailsShort } from "./TaskDetailsShort.ts";

export type TaskSearchResults = {
    /**
     * @type array
    */
    results: TaskDetailsShort[];
};