/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type TaskStatusDestroyPathParams = {
    /**
     * @description A unique integer value identifying this task status.
     * @type integer
    */
    id: number;
};

/**
 * @description No response body
*/
export type TaskStatusDestroy204 = any;

export type TaskStatusDestroyMutationResponse = TaskStatusDestroy204;

export type TaskStatusDestroyMutation = {
    Response: TaskStatusDestroy204;
    PathParams: TaskStatusDestroyPathParams;
    Errors: any;
};