/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type TasksDestroyPathParams = {
    /**
     * @description A unique integer value identifying this task.
     * @type integer
    */
    id: number;
};

/**
 * @description No response body
*/
export type TasksDestroy204 = any;

export type TasksDestroyMutationResponse = TasksDestroy204;

export type TasksDestroyMutation = {
    Response: TasksDestroy204;
    PathParams: TasksDestroyPathParams;
    Errors: any;
};