/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Task } from "./Task.ts";

export type TasksRetrievePathParams = {
    /**
     * @description A unique integer value identifying this task.
     * @type integer
    */
    id: number;
};

export type TasksRetrieve200 = Task;

export type TasksRetrieveQueryResponse = TasksRetrieve200;

export type TasksRetrieveQuery = {
    Response: TasksRetrieve200;
    PathParams: TasksRetrievePathParams;
    Errors: any;
};