/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PatchedTask } from "./PatchedTask.ts";
import type { Task } from "./Task.ts";

export type TasksPartialUpdatePathParams = {
    /**
     * @description A unique integer value identifying this task.
     * @type integer
    */
    id: number;
};

export type TasksPartialUpdate200 = Task;

export type TasksPartialUpdateMutationRequest = Omit<NonNullable<PatchedTask>, "id" | "created_by_data" | "updated_by_data" | "project_data" | "assignee_data" | "subtasks_count" | "status_data" | "created_at" | "updated_at">;

export type TasksPartialUpdateMutationResponse = TasksPartialUpdate200;

export type TasksPartialUpdateMutation = {
    Response: TasksPartialUpdate200;
    Request: TasksPartialUpdateMutationRequest;
    PathParams: TasksPartialUpdatePathParams;
    Errors: any;
};