/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { TaskStatus } from "./TaskStatus.ts";

export type TaskStatusCreate201 = TaskStatus;

export type TaskStatusCreateMutationRequest = Omit<NonNullable<TaskStatus>, "id">;

export type TaskStatusCreateMutationResponse = TaskStatusCreate201;

export type TaskStatusCreateMutation = {
    Response: TaskStatusCreate201;
    Request: TaskStatusCreateMutationRequest;
    Errors: any;
};