/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Task } from "./Task.ts";

export type TasksUpdatePathParams = {
    /**
     * @description A unique integer value identifying this task.
     * @type integer
    */
    id: number;
};

export type TasksUpdate200 = Task;

export type TasksUpdateMutationRequest = Omit<NonNullable<Task>, "id" | "created_by_data" | "updated_by_data" | "project_data" | "assignee_data" | "subtasks_count" | "status_data" | "created_at" | "updated_at">;

export type TasksUpdateMutationResponse = TasksUpdate200;

export type TasksUpdateMutation = {
    Response: TasksUpdate200;
    Request: TasksUpdateMutationRequest;
    PathParams: TasksUpdatePathParams;
    Errors: any;
};