/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type TenantTheme = {
    /**
     * @type integer
    */
    readonly id: number;
    /**
     * @type string, uri
    */
    logo_short_sm: string;
    /**
     * @type string, uri
    */
    logo_short_lg: string;
    /**
     * @type string, uri
    */
    logo_long_sm: string;
    /**
     * @type string, uri
    */
    logo_long_lg: string;
    /**
     * @type string, uri
    */
    logo_square_sm: string;
    /**
     * @type string, uri
    */
    logo_square_lg: string;
    /**
     * @type string, uri
    */
    logo_circle_sm: string;
    /**
     * @type string, uri
    */
    logo_circle_lg: string;
    /**
     * @maxLength 32
     * @type string | undefined
    */
    primary_gradient_color_1?: string;
    /**
     * @maxLength 32
     * @type string | undefined
    */
    primary_gradient_color_2?: string;
    /**
     * @minLength -2147483648
     * @maxLength 2147483647
     * @type integer | undefined
    */
    gradient_degree?: number;
    /**
     * @maxLength 100
     * @type string | undefined
    */
    font_family?: string;
    /**
     * @minLength -2147483648
     * @maxLength 2147483647
     * @type integer | undefined
    */
    default_border_radius?: number;
    /**
     * @maxLength 100
     * @type string
    */
    default_shadow: string;
    /**
     * @type integer
    */
    tenant: number;
};