/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Response } from "./Response.ts";
import type { TenantTheme } from "./TenantTheme.ts";

export type TenantsGetTenantThemeRetrieve200 = TenantTheme;

export type TenantsGetTenantThemeRetrieve404 = Response;

export type TenantsGetTenantThemeRetrieveQueryResponse = TenantsGetTenantThemeRetrieve200;

export type TenantsGetTenantThemeRetrieveQuery = {
    Response: TenantsGetTenantThemeRetrieve200;
    Errors: TenantsGetTenantThemeRetrieve404;
};