/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { TokenVerify } from "./TokenVerify.ts";

export type TokenVerifyCreate200 = Omit<NonNullable<TokenVerify>, "token">;

export type TokenVerifyCreateMutationRequest = TokenVerify;

export type TokenVerifyCreateMutationResponse = TokenVerifyCreate200;

export type TokenVerifyCreateMutation = {
    Response: TokenVerifyCreate200;
    Request: TokenVerifyCreateMutationRequest;
    Errors: any;
};