/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { TokenBlacklist } from "./TokenBlacklist.ts";

export type TokenBlacklistCreate200 = Omit<NonNullable<TokenBlacklist>, "refresh">;

export type TokenBlacklistCreateMutationRequest = TokenBlacklist;

export type TokenBlacklistCreateMutationResponse = TokenBlacklistCreate200;

export type TokenBlacklistCreateMutation = {
    Response: TokenBlacklistCreate200;
    Request: TokenBlacklistCreateMutationRequest;
    Errors: any;
};