/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { TokenRefresh } from "./TokenRefresh.ts";

export type TokenRefreshCreate200 = Omit<NonNullable<TokenRefresh>, "refresh">;

export type TokenRefreshCreateMutationRequest = Omit<NonNullable<TokenRefresh>, "access">;

export type TokenRefreshCreateMutationResponse = TokenRefreshCreate200;

export type TokenRefreshCreateMutation = {
    Response: TokenRefreshCreate200;
    Request: TokenRefreshCreateMutationRequest;
    Errors: any;
};