/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type TokenObtainPair = {
    /**
     * @type string
    */
    email: string;
    /**
     * @type string
    */
    password: string;
    /**
     * @type string
    */
    readonly access: string;
    /**
     * @type string
    */
    readonly refresh: string;
};