/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { TokenObtainPair } from "./TokenObtainPair.ts";

export type TokenCreate200 = Omit<NonNullable<TokenObtainPair>, "email" | "password">;

export type TokenCreateMutationRequest = Omit<NonNullable<TokenObtainPair>, "access" | "refresh">;

export type TokenCreateMutationResponse = TokenCreate200;

export type TokenCreateMutation = {
    Response: TokenCreate200;
    Request: TokenCreateMutationRequest;
    Errors: any;
};