/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type TokenRefresh = {
    /**
     * @type string
    */
    readonly access: string;
    /**
     * @type string
    */
    refresh: string;
};