/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export const typeEnumEnum = {
    "private": "private",
    "group": "group"
} as const;

export type TypeEnumEnum = (typeof typeEnumEnum)[keyof typeof typeEnumEnum];

/**
 * @description * `private` - Private\n* `group` - Group
*/
export type TypeEnum = TypeEnumEnum;