/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type UserProject = {
    /**
     * @type string
    */
    project__title: string;
    /**
     * @type integer
    */
    project__id: number;
    /**
     * @type string
    */
    project__owner__name: string;
};