/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CurrentUserDetail } from "./CurrentUserDetail.ts";

export type UsersRetrievePathParams = {
    /**
     * @description A unique integer value identifying this user.
     * @type integer
    */
    id: number;
};

export type UsersRetrieve200 = CurrentUserDetail;

export type UsersRetrieveQueryResponse = UsersRetrieve200;

export type UsersRetrieveQuery = {
    Response: UsersRetrieve200;
    PathParams: UsersRetrievePathParams;
    Errors: any;
};