/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


/**
 * @description User model w/o password
*/
export type UserDetails = {
    /**
     * @type integer
    */
    readonly pk: number;
    /**
     * @type string, email
    */
    readonly email: string;
    /**
     * @type string
    */
    readonly first_name: string;
    /**
     * @type string
    */
    readonly last_name: string;
};