/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PaginatedUserProjectList } from "./PaginatedUserProjectList.ts";

export type UsersProjectsListPathParams = {
    /**
     * @description A unique integer value identifying this user.
     * @type integer
    */
    id: number;
};

export type UsersProjectsListQueryParams = {
    /**
     * @description A page number within the paginated result set.
     * @type integer | undefined
    */
    page_no?: number;
    /**
     * @description Number of results to return per page.
     * @type integer | undefined
    */
    page_size?: number;
};

export type UsersProjectsList200 = PaginatedUserProjectList;

export type UsersProjectsListQueryResponse = UsersProjectsList200;

export type UsersProjectsListQuery = {
    Response: UsersProjectsList200;
    PathParams: UsersProjectsListPathParams;
    QueryParams: UsersProjectsListQueryParams;
    Errors: any;
};