/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { UserRelationShort } from "./UserRelationShort.ts";

export type UserSearchResults = {
    /**
     * @type array
    */
    results: UserRelationShort[];
};