/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { User } from "./User.ts";

export type UsersUpdatePathParams = {
    /**
     * @description A unique integer value identifying this user.
     * @type integer
    */
    id: number;
};

export type UsersUpdate200 = User;

export type UsersUpdateMutationRequest = Omit<NonNullable<User>, "id">;

export type UsersUpdateMutationResponse = UsersUpdate200;

export type UsersUpdateMutation = {
    Response: UsersUpdate200;
    Request: UsersUpdateMutationRequest;
    PathParams: UsersUpdatePathParams;
    Errors: any;
};