/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type UsersDestroyPathParams = {
    /**
     * @description A unique integer value identifying this user.
     * @type integer
    */
    id: number;
};

/**
 * @description No response body
*/
export type UsersDestroy204 = any;

export type UsersDestroyMutationResponse = UsersDestroy204;

export type UsersDestroyMutation = {
    Response: UsersDestroy204;
    PathParams: UsersDestroyPathParams;
    Errors: any;
};