/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { User } from "./User.ts";

export type UsersCreate201 = User;

export type UsersCreateMutationRequest = Omit<NonNullable<User>, "url">;

export type UsersCreateMutationResponse = UsersCreate201;

export type UsersCreateMutation = {
    Response: UsersCreate201;
    Request: UsersCreateMutationRequest;
    Errors: any;
};