/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PatchedUser } from "./PatchedUser.ts";
import type { User } from "./User.ts";

export type UsersPartialUpdatePathParams = {
    /**
     * @description A unique integer value identifying this user.
     * @type integer
    */
    id: number;
};

export type UsersPartialUpdate200 = User;

export type UsersPartialUpdateMutationRequest = Omit<NonNullable<PatchedUser>, "url">;

export type UsersPartialUpdateMutationResponse = UsersPartialUpdate200;

export type UsersPartialUpdateMutation = {
    Response: UsersPartialUpdate200;
    Request: UsersPartialUpdateMutationRequest;
    PathParams: UsersPartialUpdatePathParams;
    Errors: any;
};