/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { UserSearchResults } from "./UserSearchResults.ts";

export type UsersSearchRetrieveQueryParams = {
    /**
     * @description Search query for user names
     * @type string | undefined
    */
    q?: string;
};

export type UsersSearchRetrieve200 = UserSearchResults;

export type UsersSearchRetrieveQueryResponse = UsersSearchRetrieve200;

export type UsersSearchRetrieveQuery = {
    Response: UsersSearchRetrieve200;
    QueryParams: UsersSearchRetrieveQueryParams;
    Errors: any;
};