/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PaginatedUserList } from "./PaginatedUserList.ts";

export type UsersListQueryParams = {
    /**
     * @description A page number within the paginated result set.
     * @type integer | undefined
    */
    page_no?: number;
    /**
     * @description Number of results to return per page.
     * @type integer | undefined
    */
    page_size?: number;
};

export type UsersList200 = PaginatedUserList;

export type UsersListQueryResponse = UsersList200;

export type UsersListQuery = {
    Response: UsersList200;
    QueryParams: UsersListQueryParams;
    Errors: any;
};