/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/api/client.ts";
import type { SchemaRetrieveQueryResponse, SchemaRetrieveQueryParams } from "../../types/SchemaRetrieve.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/api/client.ts";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const schemaRetrieveSuspenseQueryKey = (params?: SchemaRetrieveQueryParams) => [{ url: '/api/schema/' }, ...(params ? [params] : [])] as const

export type SchemaRetrieveSuspenseQueryKey = ReturnType<typeof schemaRetrieveSuspenseQueryKey>

/**
 * @description OpenApi3 schema for this API. Format can be selected via content negotiation.- YAML: application/vnd.oai.openapi- JSON: application/vnd.oai.openapi+json
 * {@link /api/schema/}
 */
export async function schemaRetrieveSuspense(params?: SchemaRetrieveQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<SchemaRetrieveQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/api/schema/`, params, ... requestConfig })  
  return res.data
}

export function schemaRetrieveSuspenseQueryOptions(params?: SchemaRetrieveQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = schemaRetrieveSuspenseQueryKey(params)
  return queryOptions<SchemaRetrieveQueryResponse, ResponseErrorConfig<Error>, SchemaRetrieveQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return schemaRetrieveSuspense(params, config)
   },
  })
}

/**
 * @description OpenApi3 schema for this API. Format can be selected via content negotiation.- YAML: application/vnd.oai.openapi- JSON: application/vnd.oai.openapi+json
 * {@link /api/schema/}
 */
export function useSchemaRetrieveSuspense<TData = SchemaRetrieveQueryResponse, TQueryKey extends QueryKey = SchemaRetrieveSuspenseQueryKey>(params?: SchemaRetrieveQueryParams, options: 
{
  query?: Partial<UseSuspenseQueryOptions<SchemaRetrieveQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? schemaRetrieveSuspenseQueryKey(params)

  const query = useSuspenseQuery({
   ...schemaRetrieveSuspenseQueryOptions(params, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}