/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/api/client.ts";
import type { ConversationsCreateMutationRequest, ConversationsCreateMutationResponse } from "../../types/ConversationsCreate.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/api/client.ts";
import type { UseMutationOptions, QueryClient } from "@tanstack/react-query";
import { useMutation } from "@tanstack/react-query";

export const conversationsCreateMutationKey = () => [{ url: '/api/conversations/' }] as const

export type ConversationsCreateMutationKey = ReturnType<typeof conversationsCreateMutationKey>

/**
 * {@link /api/conversations/}
 */
export async function conversationsCreate(data: ConversationsCreateMutationRequest, config: Partial<RequestConfig<ConversationsCreateMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<ConversationsCreateMutationResponse, ResponseErrorConfig<Error>, ConversationsCreateMutationRequest>({ method : "POST", url : `/api/conversations/`, data : requestData, ... requestConfig })  
  return res.data
}

/**
 * {@link /api/conversations/}
 */
export function useConversationsCreate<TContext>(options: 
{
  mutation?: UseMutationOptions<ConversationsCreateMutationResponse, ResponseErrorConfig<Error>, {data: ConversationsCreateMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<ConversationsCreateMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? conversationsCreateMutationKey()

  return useMutation<ConversationsCreateMutationResponse, ResponseErrorConfig<Error>, {data: ConversationsCreateMutationRequest}, TContext>({
    mutationFn: async({ data }) => {
      return conversationsCreate(data, config)
    },
    mutationKey,
    ...mutationOptions
  }, queryClient)
}