/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/api/client.ts";
import type { ConversationsListQueryResponse, ConversationsListQueryParams } from "../../types/ConversationsList.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/api/client.ts";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const conversationsListQueryKey = (params?: ConversationsListQueryParams) => [{ url: '/api/conversations/' }, ...(params ? [params] : [])] as const

export type ConversationsListQueryKey = ReturnType<typeof conversationsListQueryKey>

/**
 * {@link /api/conversations/}
 */
export async function conversationsList(params?: ConversationsListQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<ConversationsListQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/api/conversations/`, params, ... requestConfig })  
  return res.data
}

export function conversationsListQueryOptions(params?: ConversationsListQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = conversationsListQueryKey(params)
  return queryOptions<ConversationsListQueryResponse, ResponseErrorConfig<Error>, ConversationsListQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return conversationsList(params, config)
   },
  })
}

/**
 * {@link /api/conversations/}
 */
export function useConversationsList<TData = ConversationsListQueryResponse, TQueryData = ConversationsListQueryResponse, TQueryKey extends QueryKey = ConversationsListQueryKey>(params?: ConversationsListQueryParams, options: 
{
  query?: Partial<QueryObserverOptions<ConversationsListQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? conversationsListQueryKey(params)

  const query = useQuery({
   ...conversationsListQueryOptions(params, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}