/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/api/client.ts";
import type { ConversationsMessagesListQueryResponse, ConversationsMessagesListPathParams, ConversationsMessagesListQueryParams } from "../../types/ConversationsMessagesList.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/api/client.ts";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const conversationsMessagesListQueryKey = (parent_lookup_conversation: ConversationsMessagesListPathParams["parent_lookup_conversation"], params?: ConversationsMessagesListQueryParams) => [{ url: '/api/conversations/:parent_lookup_conversation/messages/', params: {parent_lookup_conversation:parent_lookup_conversation} }, ...(params ? [params] : [])] as const

export type ConversationsMessagesListQueryKey = ReturnType<typeof conversationsMessagesListQueryKey>

/**
 * {@link /api/conversations/:parent_lookup_conversation/messages/}
 */
export async function conversationsMessagesList(parent_lookup_conversation: ConversationsMessagesListPathParams["parent_lookup_conversation"], params?: ConversationsMessagesListQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<ConversationsMessagesListQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/api/conversations/${parent_lookup_conversation}/messages/`, params, ... requestConfig })  
  return res.data
}

export function conversationsMessagesListQueryOptions(parent_lookup_conversation: ConversationsMessagesListPathParams["parent_lookup_conversation"], params?: ConversationsMessagesListQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = conversationsMessagesListQueryKey(parent_lookup_conversation, params)
  return queryOptions<ConversationsMessagesListQueryResponse, ResponseErrorConfig<Error>, ConversationsMessagesListQueryResponse, typeof queryKey>({
   enabled: !!(parent_lookup_conversation),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return conversationsMessagesList(parent_lookup_conversation, params, config)
   },
  })
}

/**
 * {@link /api/conversations/:parent_lookup_conversation/messages/}
 */
export function useConversationsMessagesList<TData = ConversationsMessagesListQueryResponse, TQueryData = ConversationsMessagesListQueryResponse, TQueryKey extends QueryKey = ConversationsMessagesListQueryKey>(parent_lookup_conversation: ConversationsMessagesListPathParams["parent_lookup_conversation"], params?: ConversationsMessagesListQueryParams, options: 
{
  query?: Partial<QueryObserverOptions<ConversationsMessagesListQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? conversationsMessagesListQueryKey(parent_lookup_conversation, params)

  const query = useQuery({
   ...conversationsMessagesListQueryOptions(parent_lookup_conversation, params, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}