/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/api/client.ts";
import type { ConversationsDestroyMutationResponse, ConversationsDestroyPathParams } from "../../types/ConversationsDestroy.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/api/client.ts";
import type { UseMutationOptions, QueryClient } from "@tanstack/react-query";
import { useMutation } from "@tanstack/react-query";

export const conversationsDestroyMutationKey = () => [{ url: '/api/conversations/:id/' }] as const

export type ConversationsDestroyMutationKey = ReturnType<typeof conversationsDestroyMutationKey>

/**
 * {@link /api/conversations/:id/}
 */
export async function conversationsDestroy(id: ConversationsDestroyPathParams["id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<ConversationsDestroyMutationResponse, ResponseErrorConfig<Error>, unknown>({ method : "DELETE", url : `/api/conversations/${id}/`, ... requestConfig })  
  return res.data
}

/**
 * {@link /api/conversations/:id/}
 */
export function useConversationsDestroy<TContext>(options: 
{
  mutation?: UseMutationOptions<ConversationsDestroyMutationResponse, ResponseErrorConfig<Error>, {id: ConversationsDestroyPathParams["id"]}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? conversationsDestroyMutationKey()

  return useMutation<ConversationsDestroyMutationResponse, ResponseErrorConfig<Error>, {id: ConversationsDestroyPathParams["id"]}, TContext>({
    mutationFn: async({ id }) => {
      return conversationsDestroy(id, config)
    },
    mutationKey,
    ...mutationOptions
  }, queryClient)
}