/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/api/client.ts";
import type { ConversationsListQueryResponse, ConversationsListQueryParams } from "../../types/ConversationsList.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/api/client.ts";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const conversationsListSuspenseQueryKey = (params?: ConversationsListQueryParams) => [{ url: '/api/conversations/' }, ...(params ? [params] : [])] as const

export type ConversationsListSuspenseQueryKey = ReturnType<typeof conversationsListSuspenseQueryKey>

/**
 * {@link /api/conversations/}
 */
export async function conversationsListSuspense(params?: ConversationsListQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<ConversationsListQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/api/conversations/`, params, ... requestConfig })  
  return res.data
}

export function conversationsListSuspenseQueryOptions(params?: ConversationsListQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = conversationsListSuspenseQueryKey(params)
  return queryOptions<ConversationsListQueryResponse, ResponseErrorConfig<Error>, ConversationsListQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return conversationsListSuspense(params, config)
   },
  })
}

/**
 * {@link /api/conversations/}
 */
export function useConversationsListSuspense<TData = ConversationsListQueryResponse, TQueryKey extends QueryKey = ConversationsListSuspenseQueryKey>(params?: ConversationsListQueryParams, options: 
{
  query?: Partial<UseSuspenseQueryOptions<ConversationsListQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? conversationsListSuspenseQueryKey(params)

  const query = useSuspenseQuery({
   ...conversationsListSuspenseQueryOptions(params, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}