/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/api/client.ts";
import type { ConversationsRetrieveQueryResponse, ConversationsRetrievePathParams } from "../../types/ConversationsRetrieve.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/api/client.ts";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const conversationsRetrieveSuspenseQueryKey = (id: ConversationsRetrievePathParams["id"]) => [{ url: '/api/conversations/:id/', params: {id:id} }] as const

export type ConversationsRetrieveSuspenseQueryKey = ReturnType<typeof conversationsRetrieveSuspenseQueryKey>

/**
 * {@link /api/conversations/:id/}
 */
export async function conversationsRetrieveSuspense(id: ConversationsRetrievePathParams["id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<ConversationsRetrieveQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/api/conversations/${id}/`, ... requestConfig })  
  return res.data
}

export function conversationsRetrieveSuspenseQueryOptions(id: ConversationsRetrievePathParams["id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = conversationsRetrieveSuspenseQueryKey(id)
  return queryOptions<ConversationsRetrieveQueryResponse, ResponseErrorConfig<Error>, ConversationsRetrieveQueryResponse, typeof queryKey>({
   enabled: !!(id),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return conversationsRetrieveSuspense(id, config)
   },
  })
}

/**
 * {@link /api/conversations/:id/}
 */
export function useConversationsRetrieveSuspense<TData = ConversationsRetrieveQueryResponse, TQueryKey extends QueryKey = ConversationsRetrieveSuspenseQueryKey>(id: ConversationsRetrievePathParams["id"], options: 
{
  query?: Partial<UseSuspenseQueryOptions<ConversationsRetrieveQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? conversationsRetrieveSuspenseQueryKey(id)

  const query = useSuspenseQuery({
   ...conversationsRetrieveSuspenseQueryOptions(id, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}