/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/api/client.ts";
import type { ConversationsUpdateMutationRequest, ConversationsUpdateMutationResponse, ConversationsUpdatePathParams } from "../../types/ConversationsUpdate.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/api/client.ts";
import type { UseMutationOptions, QueryClient } from "@tanstack/react-query";
import { useMutation } from "@tanstack/react-query";

export const conversationsUpdateMutationKey = () => [{ url: '/api/conversations/:id/' }] as const

export type ConversationsUpdateMutationKey = ReturnType<typeof conversationsUpdateMutationKey>

/**
 * {@link /api/conversations/:id/}
 */
export async function conversationsUpdate(id: ConversationsUpdatePathParams["id"], data: ConversationsUpdateMutationRequest, config: Partial<RequestConfig<ConversationsUpdateMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<ConversationsUpdateMutationResponse, ResponseErrorConfig<Error>, ConversationsUpdateMutationRequest>({ method : "PUT", url : `/api/conversations/${id}/`, data : requestData, ... requestConfig })  
  return res.data
}

/**
 * {@link /api/conversations/:id/}
 */
export function useConversationsUpdate<TContext>(options: 
{
  mutation?: UseMutationOptions<ConversationsUpdateMutationResponse, ResponseErrorConfig<Error>, {id: ConversationsUpdatePathParams["id"], data: ConversationsUpdateMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<ConversationsUpdateMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? conversationsUpdateMutationKey()

  return useMutation<ConversationsUpdateMutationResponse, ResponseErrorConfig<Error>, {id: ConversationsUpdatePathParams["id"], data: ConversationsUpdateMutationRequest}, TContext>({
    mutationFn: async({ id, data }) => {
      return conversationsUpdate(id, data, config)
    },
    mutationKey,
    ...mutationOptions
  }, queryClient)
}