/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/api/client.ts";
import type { ConversationsPartialUpdateMutationRequest, ConversationsPartialUpdateMutationResponse, ConversationsPartialUpdatePathParams } from "../../types/ConversationsPartialUpdate.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/api/client.ts";
import type { UseMutationOptions, QueryClient } from "@tanstack/react-query";
import { useMutation } from "@tanstack/react-query";

export const conversationsPartialUpdateMutationKey = () => [{ url: '/api/conversations/:id/' }] as const

export type ConversationsPartialUpdateMutationKey = ReturnType<typeof conversationsPartialUpdateMutationKey>

/**
 * {@link /api/conversations/:id/}
 */
export async function conversationsPartialUpdate(id: ConversationsPartialUpdatePathParams["id"], data?: ConversationsPartialUpdateMutationRequest, config: Partial<RequestConfig<ConversationsPartialUpdateMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<ConversationsPartialUpdateMutationResponse, ResponseErrorConfig<Error>, ConversationsPartialUpdateMutationRequest>({ method : "PATCH", url : `/api/conversations/${id}/`, data : requestData, ... requestConfig })  
  return res.data
}

/**
 * {@link /api/conversations/:id/}
 */
export function useConversationsPartialUpdate<TContext>(options: 
{
  mutation?: UseMutationOptions<ConversationsPartialUpdateMutationResponse, ResponseErrorConfig<Error>, {id: ConversationsPartialUpdatePathParams["id"], data?: ConversationsPartialUpdateMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<ConversationsPartialUpdateMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? conversationsPartialUpdateMutationKey()

  return useMutation<ConversationsPartialUpdateMutationResponse, ResponseErrorConfig<Error>, {id: ConversationsPartialUpdatePathParams["id"], data?: ConversationsPartialUpdateMutationRequest}, TContext>({
    mutationFn: async({ id, data }) => {
      return conversationsPartialUpdate(id, data, config)
    },
    mutationKey,
    ...mutationOptions
  }, queryClient)
}