/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/api/client.ts";
import type { ProjectMembersPartialUpdateMutationRequest, ProjectMembersPartialUpdateMutationResponse, ProjectMembersPartialUpdatePathParams } from "../../types/ProjectMembersPartialUpdate.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/api/client.ts";
import type { UseMutationOptions, QueryClient } from "@tanstack/react-query";
import { useMutation } from "@tanstack/react-query";

export const projectMembersPartialUpdateMutationKey = () => [{ url: '/api/project-members/:id/' }] as const

export type ProjectMembersPartialUpdateMutationKey = ReturnType<typeof projectMembersPartialUpdateMutationKey>

/**
 * {@link /api/project-members/:id/}
 */
export async function projectMembersPartialUpdate(id: ProjectMembersPartialUpdatePathParams["id"], data?: ProjectMembersPartialUpdateMutationRequest, config: Partial<RequestConfig<ProjectMembersPartialUpdateMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<ProjectMembersPartialUpdateMutationResponse, ResponseErrorConfig<Error>, ProjectMembersPartialUpdateMutationRequest>({ method : "PATCH", url : `/api/project-members/${id}/`, data : requestData, ... requestConfig })  
  return res.data
}

/**
 * {@link /api/project-members/:id/}
 */
export function useProjectMembersPartialUpdate<TContext>(options: 
{
  mutation?: UseMutationOptions<ProjectMembersPartialUpdateMutationResponse, ResponseErrorConfig<Error>, {id: ProjectMembersPartialUpdatePathParams["id"], data?: ProjectMembersPartialUpdateMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<ProjectMembersPartialUpdateMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? projectMembersPartialUpdateMutationKey()

  return useMutation<ProjectMembersPartialUpdateMutationResponse, ResponseErrorConfig<Error>, {id: ProjectMembersPartialUpdatePathParams["id"], data?: ProjectMembersPartialUpdateMutationRequest}, TContext>({
    mutationFn: async({ id, data }) => {
      return projectMembersPartialUpdate(id, data, config)
    },
    mutationKey,
    ...mutationOptions
  }, queryClient)
}