/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/api/client.ts";
import type { ProjectMembersRetrieveQueryResponse, ProjectMembersRetrievePathParams } from "../../types/ProjectMembersRetrieve.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/api/client.ts";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const projectMembersRetrieveSuspenseQueryKey = (id: ProjectMembersRetrievePathParams["id"]) => [{ url: '/api/project-members/:id/', params: {id:id} }] as const

export type ProjectMembersRetrieveSuspenseQueryKey = ReturnType<typeof projectMembersRetrieveSuspenseQueryKey>

/**
 * {@link /api/project-members/:id/}
 */
export async function projectMembersRetrieveSuspense(id: ProjectMembersRetrievePathParams["id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<ProjectMembersRetrieveQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/api/project-members/${id}/`, ... requestConfig })  
  return res.data
}

export function projectMembersRetrieveSuspenseQueryOptions(id: ProjectMembersRetrievePathParams["id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = projectMembersRetrieveSuspenseQueryKey(id)
  return queryOptions<ProjectMembersRetrieveQueryResponse, ResponseErrorConfig<Error>, ProjectMembersRetrieveQueryResponse, typeof queryKey>({
   enabled: !!(id),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return projectMembersRetrieveSuspense(id, config)
   },
  })
}

/**
 * {@link /api/project-members/:id/}
 */
export function useProjectMembersRetrieveSuspense<TData = ProjectMembersRetrieveQueryResponse, TQueryKey extends QueryKey = ProjectMembersRetrieveSuspenseQueryKey>(id: ProjectMembersRetrievePathParams["id"], options: 
{
  query?: Partial<UseSuspenseQueryOptions<ProjectMembersRetrieveQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? projectMembersRetrieveSuspenseQueryKey(id)

  const query = useSuspenseQuery({
   ...projectMembersRetrieveSuspenseQueryOptions(id, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}