/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/api/client.ts";
import type { ProjectMembersRetrieveQueryResponse, ProjectMembersRetrievePathParams } from "../../types/ProjectMembersRetrieve.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/api/client.ts";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const projectMembersRetrieveQueryKey = (id: ProjectMembersRetrievePathParams["id"]) => [{ url: '/api/project-members/:id/', params: {id:id} }] as const

export type ProjectMembersRetrieveQueryKey = ReturnType<typeof projectMembersRetrieveQueryKey>

/**
 * {@link /api/project-members/:id/}
 */
export async function projectMembersRetrieve(id: ProjectMembersRetrievePathParams["id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<ProjectMembersRetrieveQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/api/project-members/${id}/`, ... requestConfig })  
  return res.data
}

export function projectMembersRetrieveQueryOptions(id: ProjectMembersRetrievePathParams["id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = projectMembersRetrieveQueryKey(id)
  return queryOptions<ProjectMembersRetrieveQueryResponse, ResponseErrorConfig<Error>, ProjectMembersRetrieveQueryResponse, typeof queryKey>({
   enabled: !!(id),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return projectMembersRetrieve(id, config)
   },
  })
}

/**
 * {@link /api/project-members/:id/}
 */
export function useProjectMembersRetrieve<TData = ProjectMembersRetrieveQueryResponse, TQueryData = ProjectMembersRetrieveQueryResponse, TQueryKey extends QueryKey = ProjectMembersRetrieveQueryKey>(id: ProjectMembersRetrievePathParams["id"], options: 
{
  query?: Partial<QueryObserverOptions<ProjectMembersRetrieveQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? projectMembersRetrieveQueryKey(id)

  const query = useQuery({
   ...projectMembersRetrieveQueryOptions(id, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}