/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/api/client.ts";
import type { ProjectMembersCreateMutationRequest, ProjectMembersCreateMutationResponse } from "../../types/ProjectMembersCreate.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/api/client.ts";
import type { UseMutationOptions, QueryClient } from "@tanstack/react-query";
import { useMutation } from "@tanstack/react-query";

export const projectMembersCreateMutationKey = () => [{ url: '/api/project-members/' }] as const

export type ProjectMembersCreateMutationKey = ReturnType<typeof projectMembersCreateMutationKey>

/**
 * {@link /api/project-members/}
 */
export async function projectMembersCreate(data: ProjectMembersCreateMutationRequest, config: Partial<RequestConfig<ProjectMembersCreateMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<ProjectMembersCreateMutationResponse, ResponseErrorConfig<Error>, ProjectMembersCreateMutationRequest>({ method : "POST", url : `/api/project-members/`, data : requestData, ... requestConfig })  
  return res.data
}

/**
 * {@link /api/project-members/}
 */
export function useProjectMembersCreate<TContext>(options: 
{
  mutation?: UseMutationOptions<ProjectMembersCreateMutationResponse, ResponseErrorConfig<Error>, {data: ProjectMembersCreateMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<ProjectMembersCreateMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? projectMembersCreateMutationKey()

  return useMutation<ProjectMembersCreateMutationResponse, ResponseErrorConfig<Error>, {data: ProjectMembersCreateMutationRequest}, TContext>({
    mutationFn: async({ data }) => {
      return projectMembersCreate(data, config)
    },
    mutationKey,
    ...mutationOptions
  }, queryClient)
}