/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/api/client.ts";
import type { ProjectMembersUpdateMutationRequest, ProjectMembersUpdateMutationResponse, ProjectMembersUpdatePathParams } from "../../types/ProjectMembersUpdate.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/api/client.ts";
import type { UseMutationOptions, QueryClient } from "@tanstack/react-query";
import { useMutation } from "@tanstack/react-query";

export const projectMembersUpdateMutationKey = () => [{ url: '/api/project-members/:id/' }] as const

export type ProjectMembersUpdateMutationKey = ReturnType<typeof projectMembersUpdateMutationKey>

/**
 * {@link /api/project-members/:id/}
 */
export async function projectMembersUpdate(id: ProjectMembersUpdatePathParams["id"], data: ProjectMembersUpdateMutationRequest, config: Partial<RequestConfig<ProjectMembersUpdateMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<ProjectMembersUpdateMutationResponse, ResponseErrorConfig<Error>, ProjectMembersUpdateMutationRequest>({ method : "PUT", url : `/api/project-members/${id}/`, data : requestData, ... requestConfig })  
  return res.data
}

/**
 * {@link /api/project-members/:id/}
 */
export function useProjectMembersUpdate<TContext>(options: 
{
  mutation?: UseMutationOptions<ProjectMembersUpdateMutationResponse, ResponseErrorConfig<Error>, {id: ProjectMembersUpdatePathParams["id"], data: ProjectMembersUpdateMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<ProjectMembersUpdateMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? projectMembersUpdateMutationKey()

  return useMutation<ProjectMembersUpdateMutationResponse, ResponseErrorConfig<Error>, {id: ProjectMembersUpdatePathParams["id"], data: ProjectMembersUpdateMutationRequest}, TContext>({
    mutationFn: async({ id, data }) => {
      return projectMembersUpdate(id, data, config)
    },
    mutationKey,
    ...mutationOptions
  }, queryClient)
}