/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/api/client.ts";
import type { UsersListQueryResponse, UsersListQueryParams } from "../../types/UsersList.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/api/client.ts";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const usersListQueryKey = (params?: UsersListQueryParams) => [{ url: '/api/users/' }, ...(params ? [params] : [])] as const

export type UsersListQueryKey = ReturnType<typeof usersListQueryKey>

/**
 * {@link /api/users/}
 */
export async function usersList(params?: UsersListQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<UsersListQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/api/users/`, params, ... requestConfig })  
  return res.data
}

export function usersListQueryOptions(params?: UsersListQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = usersListQueryKey(params)
  return queryOptions<UsersListQueryResponse, ResponseErrorConfig<Error>, UsersListQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return usersList(params, config)
   },
  })
}

/**
 * {@link /api/users/}
 */
export function useUsersList<TData = UsersListQueryResponse, TQueryData = UsersListQueryResponse, TQueryKey extends QueryKey = UsersListQueryKey>(params?: UsersListQueryParams, options: 
{
  query?: Partial<QueryObserverOptions<UsersListQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? usersListQueryKey(params)

  const query = useQuery({
   ...usersListQueryOptions(params, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}