/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/api/client.ts";
import type { UsersProjectsListQueryResponse, UsersProjectsListPathParams, UsersProjectsListQueryParams } from "../../types/UsersProjectsList.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/api/client.ts";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const usersProjectsListQueryKey = (id: UsersProjectsListPathParams["id"], params?: UsersProjectsListQueryParams) => [{ url: '/api/users/:id/projects/', params: {id:id} }, ...(params ? [params] : [])] as const

export type UsersProjectsListQueryKey = ReturnType<typeof usersProjectsListQueryKey>

/**
 * {@link /api/users/:id/projects/}
 */
export async function usersProjectsList(id: UsersProjectsListPathParams["id"], params?: UsersProjectsListQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<UsersProjectsListQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/api/users/${id}/projects/`, params, ... requestConfig })  
  return res.data
}

export function usersProjectsListQueryOptions(id: UsersProjectsListPathParams["id"], params?: UsersProjectsListQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = usersProjectsListQueryKey(id, params)
  return queryOptions<UsersProjectsListQueryResponse, ResponseErrorConfig<Error>, UsersProjectsListQueryResponse, typeof queryKey>({
   enabled: !!(id),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return usersProjectsList(id, params, config)
   },
  })
}

/**
 * {@link /api/users/:id/projects/}
 */
export function useUsersProjectsList<TData = UsersProjectsListQueryResponse, TQueryData = UsersProjectsListQueryResponse, TQueryKey extends QueryKey = UsersProjectsListQueryKey>(id: UsersProjectsListPathParams["id"], params?: UsersProjectsListQueryParams, options: 
{
  query?: Partial<QueryObserverOptions<UsersProjectsListQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? usersProjectsListQueryKey(id, params)

  const query = useQuery({
   ...usersProjectsListQueryOptions(id, params, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}