/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/api/client.ts";
import type { UsersRetrieveQueryResponse, UsersRetrievePathParams } from "../../types/UsersRetrieve.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/api/client.ts";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const usersRetrieveSuspenseQueryKey = (id: UsersRetrievePathParams["id"]) => [{ url: '/api/users/:id/', params: {id:id} }] as const

export type UsersRetrieveSuspenseQueryKey = ReturnType<typeof usersRetrieveSuspenseQueryKey>

/**
 * {@link /api/users/:id/}
 */
export async function usersRetrieveSuspense(id: UsersRetrievePathParams["id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<UsersRetrieveQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/api/users/${id}/`, ... requestConfig })  
  return res.data
}

export function usersRetrieveSuspenseQueryOptions(id: UsersRetrievePathParams["id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = usersRetrieveSuspenseQueryKey(id)
  return queryOptions<UsersRetrieveQueryResponse, ResponseErrorConfig<Error>, UsersRetrieveQueryResponse, typeof queryKey>({
   enabled: !!(id),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return usersRetrieveSuspense(id, config)
   },
  })
}

/**
 * {@link /api/users/:id/}
 */
export function useUsersRetrieveSuspense<TData = UsersRetrieveQueryResponse, TQueryKey extends QueryKey = UsersRetrieveSuspenseQueryKey>(id: UsersRetrievePathParams["id"], options: 
{
  query?: Partial<UseSuspenseQueryOptions<UsersRetrieveQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? usersRetrieveSuspenseQueryKey(id)

  const query = useSuspenseQuery({
   ...usersRetrieveSuspenseQueryOptions(id, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}