/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/api/client.ts";
import type { UsersDestroyMutationResponse, UsersDestroyPathParams } from "../../types/UsersDestroy.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/api/client.ts";
import type { UseMutationOptions, QueryClient } from "@tanstack/react-query";
import { useMutation } from "@tanstack/react-query";

export const usersDestroyMutationKey = () => [{ url: '/api/users/:id/' }] as const

export type UsersDestroyMutationKey = ReturnType<typeof usersDestroyMutationKey>

/**
 * {@link /api/users/:id/}
 */
export async function usersDestroy(id: UsersDestroyPathParams["id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<UsersDestroyMutationResponse, ResponseErrorConfig<Error>, unknown>({ method : "DELETE", url : `/api/users/${id}/`, ... requestConfig })  
  return res.data
}

/**
 * {@link /api/users/:id/}
 */
export function useUsersDestroy<TContext>(options: 
{
  mutation?: UseMutationOptions<UsersDestroyMutationResponse, ResponseErrorConfig<Error>, {id: UsersDestroyPathParams["id"]}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? usersDestroyMutationKey()

  return useMutation<UsersDestroyMutationResponse, ResponseErrorConfig<Error>, {id: UsersDestroyPathParams["id"]}, TContext>({
    mutationFn: async({ id }) => {
      return usersDestroy(id, config)
    },
    mutationKey,
    ...mutationOptions
  }, queryClient)
}