/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/api/client.ts";
import type { UsersSearchRetrieveQueryResponse, UsersSearchRetrieveQueryParams } from "../../types/UsersSearchRetrieve.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/api/client.ts";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const usersSearchRetrieveQueryKey = (params?: UsersSearchRetrieveQueryParams) => [{ url: '/api/users/search/' }, ...(params ? [params] : [])] as const

export type UsersSearchRetrieveQueryKey = ReturnType<typeof usersSearchRetrieveQueryKey>

/**
 * {@link /api/users/search/}
 */
export async function usersSearchRetrieve(params?: UsersSearchRetrieveQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<UsersSearchRetrieveQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/api/users/search/`, params, ... requestConfig })  
  return res.data
}

export function usersSearchRetrieveQueryOptions(params?: UsersSearchRetrieveQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = usersSearchRetrieveQueryKey(params)
  return queryOptions<UsersSearchRetrieveQueryResponse, ResponseErrorConfig<Error>, UsersSearchRetrieveQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return usersSearchRetrieve(params, config)
   },
  })
}

/**
 * {@link /api/users/search/}
 */
export function useUsersSearchRetrieve<TData = UsersSearchRetrieveQueryResponse, TQueryData = UsersSearchRetrieveQueryResponse, TQueryKey extends QueryKey = UsersSearchRetrieveQueryKey>(params?: UsersSearchRetrieveQueryParams, options: 
{
  query?: Partial<QueryObserverOptions<UsersSearchRetrieveQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? usersSearchRetrieveQueryKey(params)

  const query = useQuery({
   ...usersSearchRetrieveQueryOptions(params, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}