/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/api/client.ts";
import type { UsersRetrieveQueryResponse, UsersRetrievePathParams } from "../../types/UsersRetrieve.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/api/client.ts";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const usersRetrieveQueryKey = (id: UsersRetrievePathParams["id"]) => [{ url: '/api/users/:id/', params: {id:id} }] as const

export type UsersRetrieveQueryKey = ReturnType<typeof usersRetrieveQueryKey>

/**
 * {@link /api/users/:id/}
 */
export async function usersRetrieve(id: UsersRetrievePathParams["id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<UsersRetrieveQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/api/users/${id}/`, ... requestConfig })  
  return res.data
}

export function usersRetrieveQueryOptions(id: UsersRetrievePathParams["id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = usersRetrieveQueryKey(id)
  return queryOptions<UsersRetrieveQueryResponse, ResponseErrorConfig<Error>, UsersRetrieveQueryResponse, typeof queryKey>({
   enabled: !!(id),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return usersRetrieve(id, config)
   },
  })
}

/**
 * {@link /api/users/:id/}
 */
export function useUsersRetrieve<TData = UsersRetrieveQueryResponse, TQueryData = UsersRetrieveQueryResponse, TQueryKey extends QueryKey = UsersRetrieveQueryKey>(id: UsersRetrievePathParams["id"], options: 
{
  query?: Partial<QueryObserverOptions<UsersRetrieveQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? usersRetrieveQueryKey(id)

  const query = useQuery({
   ...usersRetrieveQueryOptions(id, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}