/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/api/client.ts";
import type { UsersProjectsListQueryResponse, UsersProjectsListPathParams, UsersProjectsListQueryParams } from "../../types/UsersProjectsList.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/api/client.ts";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const usersProjectsListSuspenseQueryKey = (id: UsersProjectsListPathParams["id"], params?: UsersProjectsListQueryParams) => [{ url: '/api/users/:id/projects/', params: {id:id} }, ...(params ? [params] : [])] as const

export type UsersProjectsListSuspenseQueryKey = ReturnType<typeof usersProjectsListSuspenseQueryKey>

/**
 * {@link /api/users/:id/projects/}
 */
export async function usersProjectsListSuspense(id: UsersProjectsListPathParams["id"], params?: UsersProjectsListQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<UsersProjectsListQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/api/users/${id}/projects/`, params, ... requestConfig })  
  return res.data
}

export function usersProjectsListSuspenseQueryOptions(id: UsersProjectsListPathParams["id"], params?: UsersProjectsListQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = usersProjectsListSuspenseQueryKey(id, params)
  return queryOptions<UsersProjectsListQueryResponse, ResponseErrorConfig<Error>, UsersProjectsListQueryResponse, typeof queryKey>({
   enabled: !!(id),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return usersProjectsListSuspense(id, params, config)
   },
  })
}

/**
 * {@link /api/users/:id/projects/}
 */
export function useUsersProjectsListSuspense<TData = UsersProjectsListQueryResponse, TQueryKey extends QueryKey = UsersProjectsListSuspenseQueryKey>(id: UsersProjectsListPathParams["id"], params?: UsersProjectsListQueryParams, options: 
{
  query?: Partial<UseSuspenseQueryOptions<UsersProjectsListQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? usersProjectsListSuspenseQueryKey(id, params)

  const query = useSuspenseQuery({
   ...usersProjectsListSuspenseQueryOptions(id, params, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}