/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/api/client.ts";
import type { UsersCreateMutationRequest, UsersCreateMutationResponse } from "../../types/UsersCreate.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/api/client.ts";
import type { UseMutationOptions, QueryClient } from "@tanstack/react-query";
import { useMutation } from "@tanstack/react-query";

export const usersCreateMutationKey = () => [{ url: '/api/users/' }] as const

export type UsersCreateMutationKey = ReturnType<typeof usersCreateMutationKey>

/**
 * {@link /api/users/}
 */
export async function usersCreate(data: UsersCreateMutationRequest, config: Partial<RequestConfig<UsersCreateMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<UsersCreateMutationResponse, ResponseErrorConfig<Error>, UsersCreateMutationRequest>({ method : "POST", url : `/api/users/`, data : requestData, ... requestConfig })  
  return res.data
}

/**
 * {@link /api/users/}
 */
export function useUsersCreate<TContext>(options: 
{
  mutation?: UseMutationOptions<UsersCreateMutationResponse, ResponseErrorConfig<Error>, {data: UsersCreateMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<UsersCreateMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? usersCreateMutationKey()

  return useMutation<UsersCreateMutationResponse, ResponseErrorConfig<Error>, {data: UsersCreateMutationRequest}, TContext>({
    mutationFn: async({ data }) => {
      return usersCreate(data, config)
    },
    mutationKey,
    ...mutationOptions
  }, queryClient)
}