/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/api/client.ts";
import type { UsersPartialUpdateMutationRequest, UsersPartialUpdateMutationResponse, UsersPartialUpdatePathParams } from "../../types/UsersPartialUpdate.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/api/client.ts";
import type { UseMutationOptions, QueryClient } from "@tanstack/react-query";
import { useMutation } from "@tanstack/react-query";

export const usersPartialUpdateMutationKey = () => [{ url: '/api/users/:id/' }] as const

export type UsersPartialUpdateMutationKey = ReturnType<typeof usersPartialUpdateMutationKey>

/**
 * {@link /api/users/:id/}
 */
export async function usersPartialUpdate(id: UsersPartialUpdatePathParams["id"], data?: UsersPartialUpdateMutationRequest, config: Partial<RequestConfig<UsersPartialUpdateMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<UsersPartialUpdateMutationResponse, ResponseErrorConfig<Error>, UsersPartialUpdateMutationRequest>({ method : "PATCH", url : `/api/users/${id}/`, data : requestData, ... requestConfig })  
  return res.data
}

/**
 * {@link /api/users/:id/}
 */
export function useUsersPartialUpdate<TContext>(options: 
{
  mutation?: UseMutationOptions<UsersPartialUpdateMutationResponse, ResponseErrorConfig<Error>, {id: UsersPartialUpdatePathParams["id"], data?: UsersPartialUpdateMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<UsersPartialUpdateMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? usersPartialUpdateMutationKey()

  return useMutation<UsersPartialUpdateMutationResponse, ResponseErrorConfig<Error>, {id: UsersPartialUpdatePathParams["id"], data?: UsersPartialUpdateMutationRequest}, TContext>({
    mutationFn: async({ id, data }) => {
      return usersPartialUpdate(id, data, config)
    },
    mutationKey,
    ...mutationOptions
  }, queryClient)
}