/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/api/client.ts";
import type { UsersSearchRetrieveQueryResponse, UsersSearchRetrieveQueryParams } from "../../types/UsersSearchRetrieve.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/api/client.ts";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const usersSearchRetrieveSuspenseQueryKey = (params?: UsersSearchRetrieveQueryParams) => [{ url: '/api/users/search/' }, ...(params ? [params] : [])] as const

export type UsersSearchRetrieveSuspenseQueryKey = ReturnType<typeof usersSearchRetrieveSuspenseQueryKey>

/**
 * {@link /api/users/search/}
 */
export async function usersSearchRetrieveSuspense(params?: UsersSearchRetrieveQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<UsersSearchRetrieveQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/api/users/search/`, params, ... requestConfig })  
  return res.data
}

export function usersSearchRetrieveSuspenseQueryOptions(params?: UsersSearchRetrieveQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = usersSearchRetrieveSuspenseQueryKey(params)
  return queryOptions<UsersSearchRetrieveQueryResponse, ResponseErrorConfig<Error>, UsersSearchRetrieveQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return usersSearchRetrieveSuspense(params, config)
   },
  })
}

/**
 * {@link /api/users/search/}
 */
export function useUsersSearchRetrieveSuspense<TData = UsersSearchRetrieveQueryResponse, TQueryKey extends QueryKey = UsersSearchRetrieveSuspenseQueryKey>(params?: UsersSearchRetrieveQueryParams, options: 
{
  query?: Partial<UseSuspenseQueryOptions<UsersSearchRetrieveQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? usersSearchRetrieveSuspenseQueryKey(params)

  const query = useSuspenseQuery({
   ...usersSearchRetrieveSuspenseQueryOptions(params, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}